### ISSUE TITLE
Migration from Gigablast to Privacore

### ISSUE THREAD

**Issue by pstewart726** [privacore/open-source-search-engine#1]
Greetings!  Most interested in hearing about migration from Gigablast to Privacore.  It appears that Privacore is being actively maintained - thank you for that!

**Comment by br-privacore** [comment]
Hi there. I have created a short guide in the project README.md. It is basically copying over our new binaries and scripts, and rebuilding posdb.

Please notice that major changes are made to the on-disk merge logic, so our version will (soon anyway) require a dedicated drive or folder for merging, with space enough to hold a complete copy of posdb for a single instance.
