### ISSUE TITLE
Crash after Memory Corruption Error While Spidering

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#10]
Looks like it happened after a series of errors including growing the table, sitehash collission

Build Date 1/27/2017

20170128-023600-529 0000 006682 DBG build: Got linknode = -1 < 0. Cached linker http://www.freerepublic.com/tag/by:chickensoup/index?tab=comments;brevity=full;options=no-change does not have outlink to http://www.freerepublic.com/perl/mail-compose?reftype=comment;refid=3517115.75 like linkdb says it should. page is probably too big and the outlink is past our limit. contentLen=66886. or a sitehash collision, or an area tag link.
20170128-023600-529 0000 006682 ERR query: Had error generating msg20 reply for d=183815804907: Bad engineer
20170128-023600-529 0000 006682 ERR Msg20.cpp:sendReply:600: call sendErrorReply. error=Bad engineer
20170128-023600-531 0000 006682 WRN net: Multicast got error in reply from hostId 0 (msgType=0x20 transId=486955 nice=2 net=default): Bad engineer.

...

20170128-023603-135 0000 006682 INF spider: adding http://www.freerepublic.com/focus/f-chat/3518085/reply?c=1 to crawldelayqueue cd=500ms ip=209.157.64.200
20170128-023603-227 0000 006682 DBG table: grewtable dt8-tab from 2048 to 4096 slots in 0 ms (this=0x7f53446f8440) (used=1024)
20170128-023603-227 0000 006682 DBG table: grewtable dt8-tab from 4096 to 8192 slots in 0 ms (this=0x7f53446f8440) (used=2048)

...

20170128-023604-176 0000 006682 INF build: coll=dmoz collnum=5 ip=192.30.253.112 firstip=192.30.253.112 spidered=Jan-28-2017(07:36:04)(1485588964) scheduledtime=Jan-27-2017(23:29:19)(1485559759) discoverydate=Jan-27-2017(23:29:19)(1485559759) firsttime=1 goodinlinks=0 docid=95968668944 probdocid=95968668944 probdocidmin=95968668928 probdocidmax=95968668991 usetimeaxis=0 siteinlinks=0298 siterank=11 pageinlinks=0001 uh48=74862759355920 charset=UTF-8 ctype=html lang=00(xx) contentlen=000000 contenttruncated=0 robotstxtlen=30486 robotsallowed=0 ch32=0000000000 dh32=0213794484 sh32=2654279353 hasrssoutlink=0 addlistsize=00077 addspiderreqsize=00000 addspiderrepsize=00076 addstatusdocsize=00000 thumbnail=none utf8size=0 rawutf8size=0 urlfilternum=12 site=www.github.com siteroot=0 pathdepth=4 contentinjected=0 urlinjected=0 isaddurl=0 spiderlinks=1 crawldelayms=500 exactcontenthash=0 oldpriority=0 errcnt=0 url=https://github.com/twbs/bootstrap/blob/master/LICENSE : robots.txt disallows this url
20170128-023604-235 0000 006682 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-023604-235 0000 006682 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-023604-235 0000 006682 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 6747714330 bytes; retrying in a bit...
20170128-023604-252 0000 006682 INF build: coll=news collnum=1 ip=209.157.64.200 firstip=209.157.64.200 spidered=Jan-28-2017(07:36:04)(1485588964) scheduledtime=Jan-28-2017(06:39:15)(1485585555) discoverydate=Jan-28-2017(06:39:15)(1485585555) firsttime=1 goodinlinks=0 docid=133698000850 probdocid=133698000850 probdocidmin=133698000832 probdocidmax=133698000895 usetimeaxis=0 siteinlinks=0438 siterank=11 pageinlinks=0001 uh48=49886599161810 charset=UTF-8 ctype=html lang=00(xx) contentlen=000000 contenttruncated=0 robotstxtlen=0107 robotsallowed=0 ch32=0000000000 dh32=0615250783 sh32=0612549967 hasrssoutlink=0 addlistsize=00077 addspiderreqsize=00000 addspiderrepsize=00076 addstatusdocsize=00000 thumbnail=none utf8size=0 rawutf8size=0 urlfilternum=14 site=www.freerepublic.com siteroot=0 pathdepth=1 contentinjected=0 urlinjected=0 isaddurl=0 spiderlinks=0 crawldelayms=500 exactcontenthash=0 oldpriority=0 errcnt=0 url=http://www.freerepublic.com/perl/post?id=3436209,16 : robots.txt disallows this url
20170128-023604-276 0000 006682 INF build: https://tas.dhl.com/tas redirected to http://tas.dhl.com/tas/
20170128-023604-277 0000 006682 INF build: http://tas.dhl.com/robots.txt redirected to https://tas.dhl.com/robots.txt
20170128-023604-283 0000 006682 ERR gb: Printing stack trace
*** Error in `./gb': malloc(): memory corruption (fast): 0x00007f5281233220 ***

**Comment by br-privacore** [comment]
Do you have the core so you can generate a stack trace?

**Comment by MikeLx** [comment]
Not anymore. I'll make sure to keep them from now on.

**Comment by MikeLx** [comment]
Assuming this is fixed with new fix on master.
