### ISSUE TITLE
Crash after sitehash collision, mem underrun, etc.

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#11]
20170128-115101-321 0000 012281 DBG build: Got linknode = -1 < 0. Cached linker http://www.democraticunderground.com/ does not have outlink to http://www.democraticunderground.com/10141677861 like linkdb says it should. page is probably too big and the outlink is past our limit. contentLen=80727. or a sitehash collision, or an area tag link.
20170128-115101-321 0000 012281 ERR query: Had error generating msg20 reply for d=2822938304: Bad engineer
20170128-115101-321 0000 012281 ERR Msg20.cpp:sendReply:600: call sendErrorReply. error=Bad engineer
20170128-115101-322 0000 012281 WRN net: Multicast got error in reply from hostId 0 (msgType=0x20 transId=285804 nice=2 net=default): Bad engineer.
20170128-115101-322 0000 012281 WRN query: msg20: got reply for docid 2822938304 : Bad engineer
20170128-115101-326 0000 012281 INF build: coll=news collnum=1 ip=52.71.227.75 firstip=52.71.227.75 spidered=Jan-28-2017(16:50:54)(1485622254) scheduledtime=Jan-26-2017(02:22:13)(1485397333) discoverydate=Jan-26-2017(02:22:13)(1485397333) firsttime=0 docid=52723588835 probdocid=52723588835 probdocidmin=52723588800 probdocidmax=52723588863 usetimeaxis=0 siteinlinks=0177 siterank=10 pageinlinks=0001 uh48=183946043334243 charset=csISOLatin1 ctype=html lang=01(en) hopcount=01 contentlen=039770 robotstxtlen=1113 robotsallowed=1 ch32=2683490726 dh32=1128201083 sh32=3349639406 ispermalink=1 isrss=0 addlistsize=00077 addspiderreqsize=00000 addspiderrepsize=00076 addstatusdocsize=00000 thumbnail=none utf8size=39775 rawutf8size=39737 site=www.democraticunderground.com siteroot=0 pathdepth=0 lastindexed=Jan-28-2017(07:17:18)(1485587838) contentinjected=0 urlinjected=0 isaddurl=0 crawldelayms=500 exactcontenthash=7515314638126352382 oldurlfilternum=13 oldpriority=0 errcnt=0 url=http://www.democraticunderground.com/10141677861 : Doc unchanged
20170128-115101-394 0000 012281 ERR gb: Printing stack trace
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x53acbb
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x53adce
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x7fb075363330
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x7fb0737ed3ad
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5edfba
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x447092
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x44779c
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x59969a
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x59a12f
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x59a4c5
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x59bd10
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5a5b90
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5adcc6
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5b127a
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5b18e8
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5b25d0
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5bf029
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x486ad0
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x486938
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x486407
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5846dd
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x5850e9
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x58542e
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x53a7a6
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x53b23f
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x53b715
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x40ba2c
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x407558
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x7fb07535b184
20170128-115101-394 0000 012281 ERR addr2line -e ./gb 0x7fb07379d37d
20170128-115101-394 0000 012281 LOG mem: underrun at 7fafaa3ee944 loff=-1 size=16 i=16632 note=TcpSocket
20170128-115101-444 0000 012281 WRN mem: possible breeching buffer=msg8astate dist=20
20170128-115101-444 0000 012281 LOG mem: underrun at 7fafaa3ee944 loff=-2 size=16 i=16632 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: underrun at 7fafaa3ee944 loff=-3 size=16 i=16632 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: underrun at 7fafaa3ee944 loff=-4 size=16 i=16632 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: overrun  at 0x7fafaa3ee944 (size=16)roff=0 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: overrun  at 0x7fafaa3ee944 (size=16)roff=1 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: overrun  at 0x7fafaa3ee944 (size=16)roff=2 note=TcpSocket
20170128-115101-444 0000 012281 LOG mem: overrun  at 0x7fafaa3ee944 (size=16)roff=3 note=TcpSocket
20170128-115101-444 0000 012281 ERR gb: Printing stack trace
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x53acbb
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x4d7b69
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x4ff416
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x4ff440
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x469fca
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x46a098
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x46a001
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x4d7c33
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x53adfa
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x7fb075363330
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x7fb0737ed3ad
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x5edfba
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x447092
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x44779c
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x59969a
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x59a12f
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x59a4c5
20170128-115101-444 0000 012281 ERR addr2line -e ./gb 0x59bd10
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5a5b90
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5adcc6
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5b127a
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5b18e8
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5b25d0
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5bf029
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x486ad0
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x486938
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x486407
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5846dd
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x5850e9
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x58542e
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x53a7a6
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x53b23f
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x53b715
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x40ba2c
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x407558
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x7fb07535b184
20170128-115101-445 0000 012281 ERR addr2line -e ./gb 0x7fb07379d37d
Aborted (core dumped)

**Comment by br-privacore** [comment]
I find the memory issues you see odd. Which Linux kernel version are you using? There appears to be problems with 4.4.0-59:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1655842

**Comment by MikeLx** [comment]
root@localhost:/tmp# uname -r
4.4.0-31-generic

What kernel are you using?

**Comment by br-privacore** [comment]
A mix of 4.4.0-59-generic and 4.4.0-22-generic, primarily.

**Comment by MikeLx** [comment]
I will try these kernels and see if the issue goes away. Also, what is the maximum speed I should be spidering/host? I am running this system very fast. It is inserting, on average, about 7 docs/second with sustained spikes to 20/docs second using one host. The UDP connections are almost always over 100, Threads in the 4-14 range. Is it possible that I'm just running the system faster than I should?

**Comment by MikeLx** [comment]
I think this is fixed with switch to 4.4.0-59 kernel. Closing.
