### ISSUE TITLE
Once can't get lock, never can get it...

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#12]
20170128-172828-129 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172828-130 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172828-130 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...
20170128-172833-133 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172833-133 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172833-133 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...
20170128-172838-136 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172838-136 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172838-136 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...
20170128-172843-139 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172843-139 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172843-139 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...
20170128-172848-142 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172848-142 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172848-142 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...
20170128-172853-094 0000 016218 INF Attempted merge, but merge already running
20170128-172853-145 0000 016218 TRC RdbMerge::getLockWrapper(0x149fa80)
20170128-172853-145 0000 016218 DBG Rdbmerge(0x149fa80)::getLock(), m_rdbId=16
20170128-172853-145 0000 016218 INF Rdbmerge(0x149fa80)::getLock(), m_rdbId=16: Didn't get lock for 7168304790 bytes; retrying in a bit...

on and on into perpetuity...

**Comment by br-privacore** [comment]
Do you have 7168304790 bytes free on your merge drive? Please show the content of your merge drive's merge space and merge locks dirs.

**Comment by MikeLx** [comment]
Should have plenty of space. I think it just got very corrupted and couldn't read it. The DB eventually just broke. Wouldn't even start back up. Saved the contents of the merge directories put there wasn't much of anything there. Mostly just a bunch of empty directories for the collections. Here is the output:

root@localhost:/tmp# du -sh gb_merge_locks
4.0K    gb_merge_locks
root@localhost:/tmp# du -sh gb_merge_space
72K     gb_merge_space

root@localhost:/# df
Filesystem                     1K-blocks     Used Available Use% Mounted on
udev                            82454232        4  82454228   1% /dev
tmpfs                           16499828      704  16499124   1% /run
/dev/dm-0                        9480420  3747728   5228068  42% /
none                                   4        0         4   0% /sys/fs/cgroup
none                                5120        0      5120   0% /run/lock
none                            82499128        0  82499128   0% /run/shm
none                              102400        0    102400   0% /run/user
/dev/mapper/localhost--vg-home 129044116 64969380  57496560  54% /home
/dev/sda1                         240972    41367    187164  19% /boot

**Comment by br-privacore** [comment]
What got corrupted? We need more details to dig into this. I'd like to see the actual content of gb_merge_locks and gb_merge_space, to see if a gb instance holds a lock "forever". I'd suggest you try creating a folder for merging outside of the /tmp partition.

**Comment by MikeLx** [comment]
Let me do that. This is a small drive just for testing and it's being used for a bunch of things simultaneously. I'll move this project into the production system. I do think this is most likely a space issue.

**Comment by alc-privacore** [comment]
/dev/dm-0 9480420 3747728 5228068 42% /

Doesn't look like /tmp has enough space. Most of the space seems to be allocated for /home and /dev

Just a curious question, what was the log file showing when you're unable to start gb anymore?

**Comment by MikeLx** [comment]
This was a space issue. I changed the drives and all this problem hasn't come back.
