### ISSUE TITLE
Aborted while spidering 'std::length_error' what():  basic_string::_S_create

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#13]
Says core dumped but can't find core. Are cores still dumped into coll directory? I moved this to another drive but still getting this error.  Ubuntu 14.04.5 g++ 4.9.4

20170129-185920-666 0000 003642 INF spider: adding http://message.snopes.com/forumdisplay.php?f=5 to crawldelayqueue cd=500ms ip=199.189.107.4
20170129-185920-671 0000 003642 INF build: http://manager.videoplaza.com/karbon/admin/Application.html redirected to https://manager.videoplaza.com/karbon/admin/Application.html
20170129-185920-676 0000 003642 WRN net: Multicast got error in reply from hostId 0 (msgType=0x20 transId=709175 nice=2 net=default): Bad engineer.
20170129-185920-676 0000 003642 WRN query: msg20: got reply for docid 262131862629 : Bad engineer
20170129-185920-712 0000 003642 INF build: coll=dmozseed collnum=1 ip=104.16.41.51 firstip=104.16.41.51 spidered=Jan-29-2017(23:59:14)(1485734354) scheduledtime=Jan-29-2017(23:19:04)(1485731944) discoverydate=Jan-29-2017(23:19:04)(1485731944) firstindexed=Jan-29-2017(23:59:14)(1485734354) firsttime=1 goodinlinks=0 docid=44429377845 probdocid=44429377845 probdocidmin=44429377792 probdocidmax=44429377855 usetimeaxis=0 siteinlinks=0142 siterank=10 pageinlinks=0001 uh48=68489028211957 charset=UTF-8 ctype=html lang=01(en) country=14(au) hopcount=01 contentlen=138515 contenttruncated=0 robotstxtlen=0033 robotsallowed=1 ch32=0908990373 dh32=1203629828 sh32=0035803719 ispermalink=1 isrss=0 hasrssoutlink=1 outlinksadded=0180 addlistsize=150912 addspiderreqsize=00000 addspiderrepsize=00076 addstatusdocsize=00000 thumbnail=none utf8size=138516 rawutf8size=138614 priority=0 urlfilternum=12 site=www.lifehacker.com.au siteroot=0 pathdepth=2 contentinjected=0 urlinjected=0 isaddurl=0 spiderlinks=1 crawldelayms=500 exactcontenthash=2378479241438625621 isadult=1 errcnt=0 redir=http://www.lifehacker.com.au/2017/01/how-to-tell-if-your-childs-educational-needs-are-being-met-at-school/ url=http://www.lifehacker.com.au/2017/01/how-to-tell-if-your-childs-educational-needs-are-being-met-at-school : Success
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
Aborted (core dumped)

**Comment by alc-privacore** [comment]
All core related files have been renamed to lastcore.*
lastcore.core will be the corefile you want.

**Comment by MikeLx** [comment]
I can't find the core anywhere. It doesn't look like it dumped successfully.

**Comment by MikeLx** [comment]
Closing with new fix on master.
