### ISSUE TITLE
Can't set spider priority in URL Filters

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#18]
Can't set spider priority in URL Filters

**Comment by alc-privacore** [comment]
Which url filter profile are you using?

**Comment by MikeLx** [comment]
Custom

**Comment by br-privacore** [comment]
Confirmed. Looks like a bug.

**Comment by ghost** [comment]
Fixed in commit 51484abe432dd6fadd7610b915c1b391dc08022a
