### ISSUE TITLE
./gb start won't start hosts

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#19]
When issuing the ./gb start command on host 0, no hosts start. Hosts must be started manually by issuing ./gb command in each host directory individually. Save & Exit will close all hosts.

**Comment by alc-privacore** [comment]
What do you see on the screen after issuing ./gb start?
Is gbstart.sh available? Is it executable?

**Comment by MikeLx** [comment]
Here is the output.

osse@localhost:/mnt/sam850pro2tb0/cluster1/osse0$ ./gb start
admin: ssh 192.168.0.30 '/mnt/sam850pro2tb0/cluster1/osse0/gbstart.sh 0' &
admin: ssh 192.168.0.30 '/mnt/sam850pro2tb0/cluster1/osse1/gbstart.sh 1' &
admin: ssh 192.168.0.30 '/mnt/sam850pro2tb0/cluster1/osse2/gbstart.sh 2' &
admin: ssh 192.168.0.30 '/mnt/sam850pro2tb0/cluster1/osse3/gbstart.sh 3' &

**Comment by alc-privacore** [comment]
Could you try to run
ssh 192.168.0.30
and see if you could connect without any password/prompt?

**Comment by MikeLx** [comment]
Connects just fine. I'm actually running the four node cluster just fine. I have to start each host individually using ./gb to do it though...

**Comment by MikeLx** [comment]
Looks like this was caused by pdftohtml not being installed. Installed it. seems to be working with the exception of one host not starting up. This host had previously crashed with a memory error. Probably related to that. Might be looking for a core before it will start but cores never dump on my system for some reason. Will recompile from the start and if it works I will close this issue.

**Comment by br-privacore** [comment]
if there is a fatal_error file in the folder it won't start - because it is fatal, and something you need to look into.

**Comment by MikeLx** [comment]
Ahhh.... What is the name and location of the error file?

**Comment by MikeLx** [comment]
Found it. fatal_error. duhh...
