### ISSUE TITLE
Compile issue Ubuntu 16.1

### ISSUE THREAD

**Issue by pstewart726** [privacore/open-source-search-engine#2]
Trying to compile on Ubuntu 16.1 release and getting error with make:

root@spider01:/pc/0# make -j4
rm -f Version.o
g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wno-nonnull-compare -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wsuggest-final-types -Wsuggest-final-methods -Wno-invalid-offsetof -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-result              -c Entities.cpp
g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wno-nonnull-compare -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wsuggest-final-types -Wsuggest-final-methods -Wno-invalid-offsetof -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-result              -c GbMutex.cpp
g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wno-nonnull-compare -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wsuggest-final-types -Wsuggest-final-methods -Wno-invalid-offsetof -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-result              -c HashTable.cpp
g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wno-nonnull-compare -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wsuggest-final-types -Wsuggest-final-methods -Wno-invalid-offsetof -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-result              -c HighFrequencyTermShortcuts.cpp
Entities.cpp: In function ‘bool initEntityTable()’:
Entities.cpp:36:37: error: ‘s_entities’ was not declared in this scope
   const int32_t n = (int32_t)sizeof(s_entities) / (int32_t)sizeof(Entity);
                                     ^~~~~~~~~~
Entities.cpp: In function ‘const Entity* getTextEntity(const char*, int32_t)’:
Entities.cpp:83:9: error: ‘s_entities’ was not declared in this scope
  return s_entities+i-1;
         ^~~~~~~~~~
g++ -D_REENTRANT_ -I. -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wno-nonnull-compare -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wsuggest-final-types -Wsuggest-final-methods -Wno-invalid-offsetof -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-result              -c HttpMime.cpp
Entities.cpp: In function ‘int32_t getEntity_a(const char*, int32_t, uint32_t*, int32_t*, int32_t*)’:
Entities.cpp:206:32: error: ‘max_entity_name_len’ was not declared in this scope
  while ( len < maxLen && len < max_entity_name_len && is_alnum_a( s[len] ) ) {
                                ^~~~~~~~~~~~~~~~~~~
Entities.cpp:220:13: error: ‘max_entity_name_len’ was not declared in this scope
  if ( len > max_entity_name_len+1 ) {
             ^~~~~~~~~~~~~~~~~~~
Makefile:419: recipe for target 'Entities.o' failed
make: *** [Entities.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by br-privacore** [comment]
We are using Ubuntu 14.04 with g++ 4.9.3 and it compiles fine. If you can try that, please do.

**Comment by pstewart726** [comment]
Thank you - I'll see if I can create a new environment with 14.04 .. appreciate the fast response and reference to your dev environment.  Thank you.

**Comment by alc-privacore** [comment]
Just a note. This looks to be caused by empty entities.inc file. Removing that file and recompiling should fix the error (with the condition that python2 is installed).

**Comment by br-privacore** [comment]
Thanks Ai Lin. README updated.
