### ISSUE TITLE
Just migrated from GB to privacore

### ISSUE THREAD

**Issue by unisqu** [privacore/open-source-search-engine#20]
I've deleted all rm -rf posdb* files from coll.main.0/

i've clicked on the Yes and saved "posdb rebuilt". Nothing happens. There's no new posdb* inside coll.main.0 even after a restart.

Is this ok?

collection to rebuild
Name of collection to rebuild. REQUIRED <- should I enter something here?

**Comment by alc-privacore** [comment]
> Is this ok?

No. Doesn't look like your rebuild was started successfully.

> Name of collection to rebuild. REQUIRED <- should I enter something here?

Yes. You should enter your collection name here.

Your configuration should look similar to the image below (replace the collection name with your collection name) before clicking on the "NO" for "rebuild mode enabled".
![posdb_rebuild](https://cloud.githubusercontent.com/assets/15614066/22688038/cbe7e03e-ed2a-11e6-81b5-b2983b022d62.png)
