### ISSUE TITLE
Program received signal SIGILL, Illegal instruction error on new Intel system. Can't run.

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#23]
Getting this error after compiling new version. Isn't happening on AMD machines. Maybe I missed a package?

(gdb) run ./gb
Starting program: /home/osse/open-source-search-engine/gb ./gb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00000000004324b4 in Conf::Conf (this=0xd258e0 <g_conf>) at Conf.cpp:107
107             m_termFreqWeightFreqMin = 0.0;
(gdb) bt
#0  0x00000000004324b4 in Conf::Conf (this=0xd258e0 <g_conf>) at Conf.cpp:107
#1  0x00000000004339be in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535) at Conf.cpp:17
#2  0x00000000004339e8 in _GLOBAL__sub_I_g_conf () at Conf.cpp:562
#3  0x000000000060793d in __libc_csu_init ()
#4  0x00007ffff5d09ed5 in __libc_start_main (
    main=0x408226 <main(int, char**)>, argc=2, argv=0x7fffffffe6b8,
    init=0x6078f0 <__libc_csu_init>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe6a8) at libc-start.c:246
#5  0x0000000000407c60 in _start ()
(gdb)

**Comment by alc-privacore** [comment]
Makefile
```
ifeq ($(ARCH), x86_64)
CPPFLAGS += -march=core-avx-i -msse4.2
endif
```

Try replacing that block to
```
ifeq ($(ARCH), x86_64)
CPPFLAGS += -march=native
endif
```

See if it works.

**Comment by MikeLx** [comment]
This worked. Thanks!
