### ISSUE TITLE
How do I free my port 80 on

### ISSUE THREAD

**Issue by mehmet-biter** [privacore/open-source-search-engine#25]
Failed to bind socket on port 80: Permission denied.Are you already running gb?If not, try editing ./hosts.conf tochange the port from 80 to something bigger.Or stop gb by running 'gb stop' or by clicking'save & exit' in the master controls.

**Comment by br-privacore** [comment]
You provided the answer yourself. Either gb, or something else, is already using port 80. change the port number in hosts.conf to something else, or stop the other program using port 80.

**Comment by mehmet-biter** [comment]
Yes but i wanna make it like this xxx.com:8000 not this get xxx.com
