### ISSUE TITLE
gb start silently fails

### ISSUE THREAD

**Issue by turbo** [privacore/open-source-search-engine#30]
Hi.

Current build builds fine, and one instance alone runs fine, too. After doing a (successful) `gb install`, starting the cluster fails silently:

```text
root@privacore-xlarge:/media/large/inst0# ./gb start
admin: ssh 127.0.0.1 '/media/large/inst0/gbstart.sh 0' &
admin: ssh 127.0.0.1 '/media/large/inst1/gbstart.sh 1' &
admin: ssh 127.0.0.1 '/media/large/inst2/gbstart.sh 2' &
admin: ssh 127.0.0.1 '/media/large/inst3/gbstart.sh 3' &
root@privacore-xlarge:/media/large/inst0#
```

According to top, not a single gb process is start. I can start each gb manually, but ofc the other hosts will show up as dead.

**Comment by turbo** [comment]
And no, there's not fatal_error file generated (https://github.com/privacore/open-source-search-engine/issues/19).

Yes, local SSH works (otherwise the install would've failed.

**Comment by alc-privacore** [comment]
Is pdftohtml installed on the machine? The startup script also checks if the necessary converters are available.
