### ISSUE TITLE
How to install the script/

### ISSUE THREAD

**Issue by promauriya** [privacore/open-source-search-engine#32]
I downloaded the zip file and decompressed through command prompt in Ubuntu. Then, I followed the same step as you do for Gigablast but when you run "make -j2" command. 
It shows:-
GbRegex.h:4:18 fatal error: pcre.h: No such file or directory compilation terminated.
Makefile:436: recipe for target 'Msge0.o' failed
make: *** [Msge0.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by romcio** [comment]
Hi,
try to  install: sudo apt-get install libpcre3-dev  before.

**Comment by promauriya** [comment]
Now another error arises.
SearchInput.cpp:12:54: fatal error: third-party/cld2/public/compact_lang_det.h: No such file or directory
compilation terminated.
Makefile:436: recipe for target 'SearchInput.o' failed
make: *** [SearchInput.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by alc-privacore** [comment]
Try running: 
git submodule init
git submodule update

**Comment by promauriya** [comment]
I downloaded the zip file from the repository and tried to it as gigablast. I was stuck when i ran:
"make -j2"
GbRegex.h:4:18 fatal error: pcre.h: No such file or directory compilation terminated.
Makefile:436: recipe for target 'Msge0.o' failed
make: *** [Msge0.o] Error 1
make: *** Waiting for unfinished jobs....

It got me through the error with "sudo apt-get install libpcre3-dev".
Now, I am stuck with 
SearchInput.cpp:12:54: fatal error: third-party/cld2/public/compact_lang_det.h: No such file or directory
compilation terminated.
Makefile:436: recipe for target 'SearchInput.o' failed
make: *** [SearchInput.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by mehmet-biter** [comment]
gb: GbMutex.cpp:18: GbMutex::~GbMutex(): Assertion `rc==0' failed.

**Comment by br-privacore** [comment]
Our primary platform is Ubuntu 16.04, so I suggest you test on that.

First, make sure all dependencies mentioned in the README.md is installed. 

Second:
git clone https://github.com/privacore/open-source-search-engine.git
cd open-source-search-engine
git submodule init
git submodule update
make -j8

**Comment by lisawebcoder** [comment]
hello i tried running the original gb but it fails and doesnt make the gb folder and file gb.conf
so i am trying oyur version in ubuntu 18
will it work ?

Lisa

**Comment by lisawebcoder** [comment]
hello i built the project and got no errors where there is no gb folder 
is it then then command ./gb?
where is the gb or c++ execuatble plz?

Lisa

**Comment by lisawebcoder** [comment]
hello i completed the make and i got the no erros
how exactly do you stop all gb instances in spite of the fact there is No gb folder or gb.conf file
how do you copy the tar file?

Lisa
plz reply thank you


Copy | Stop your running GB instances. Copy the files contained in the new gb-[date]-[rev].tar.gz file to your GB instance 0.


-- | --
Install | Go to your GB instance 0 and do a './gb install' to copy the binary and needed files to all instances.
Remove files | Remove the posdb files from your collections
Convert files | Convert the spiderdb files to sqlite3 format by using './gb convertspiderdb'
Start | './gb start' from your instance 0 and you should be on your way.
Rebuild | Rebuild the posdb data files through the web UI. This is needed

**Comment by brianrasmusson** [comment]
Lisa, I saw all your questions on the original Gigablast. If you cannot even get it built and running, trust me, Gigablast is not for you. You will experience even more problems once you get it up and running.

We dropped our project based on it because of major problems with the code base, even after working on it for years.

Find another search engine - Gigablast is dead.

**Comment by lisawebcoder** [comment]
no i want to fix it 

thanx 
Lisa

**Comment by brianrasmusson** [comment]
Gigablast is dead.

You won't find anybody to help with it.

This is my last comment.

**Comment by lisawebcoder** [comment]
can you kindly provide the correct make command plz? if possible
I getting diffrent eroors for different syntax

make
make -j2

make -j
make -j8
make -j4

i am in ubuntu Vbox 18
maybe i also need to go ubuntu 16

i respect you did many years of trials

thats incredible

Lisa

**Comment by lisawebcoder** [comment]
thank you sir for taking the time

and good day
regards
