### ISSUE TITLE
Possible bugs in source code

### ISSUE THREAD

**Issue by mehmet-biter** [privacore/open-source-search-engine#37]
gb: GbMutex.cpp:18: GbMutex::~GbMutex(): Assertion `rc==0' failed.

**Comment by br-privacore** [comment]
You have to provide more details. Version, stack trace, OS - the more details the better, otherwise we cannot help you.

**Comment by mehmet-biter** [comment]
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

memetb@memetb:~/open-source-search-engine1$ ./gb 0
-bash: ./gb: Böyle bir dosya ya da dizin yok
memetb@memetb:~/open-source-search-engine1$ cd
memetb@memetb:~$ cd open-source-search-engine
memetb@memetb:~/open-source-search-engine$ ./gb 0
20171002-120016-205 0000 001752 INF disk: call to open(/home/memetb/open-source-search-engine/tmpfile) blocked for 23 ms.
20171002-120016-233 0000 001752 INI conf: Gigablast Version      : Sep 29 2017 04:41:52
20171002-120016-233 0000 001752 INI conf: Gigablast Architecture : 64-bit
20171002-120016-233 0000 001752 INI conf: Gigablast Build config : release
20171002-120016-233 0000 001752 INI conf: Gigablast Git commit   : 4bd1ecf25a397356022994941354428a841b1240
20171002-120016-233 0000 001752 DBG host: Working directory is /home/memetb/open-source-search-engine/
20171002-120016-233 0000 001752 DBG host: Using /home/memetb/open-source-search-engine/hosts.conf
20171002-120016-233 0000 001752 DBG host: Process ID is 1751
20171002-120016-233 0000 001752 DBG host: Detected local ip 127.0.0.1
20171002-120016-233 0000 001752 DBG host: Detected local ip 192.168.1.37
20171002-120016-233 0000 001752 DBG host: Running as host id #0
20171002-120016-507 0000 001752 INF wikt: Loading /home/memetb/open-source-search-engine/wiktionary-syns.dat
20171002-120017-580 0000 001752 INF wikt: Loading /home/memetb/open-source-search-engine/wiktionary-buf.txt
20171002-120018-066 0000 001752 DBG wikt: test "love" -> "en|love,loved,loving,loves"
20171002-120018-067 0000 001752 INF wiki: Loading /home/memetb/open-source-search-engine/wikititles2.dat
20171002-120018-073 0000 001752 INF mem: addMem(100663296): tbl-wiki. ptr=0x7f3e8285f014 used=126978143
20171002-120019-111 0000 001752 INF db: Loading conf for collection main (0)
20171002-120019-129 0000 001752 DBG table: grewtable enttbl from 4096 to 8192 slots in 0 ms (this=0x9d85a0) (used=2048)
20171002-120019-260 0000 001752 INF mem: addMem(349879400): buckets-posdb. ptr=0x7f3e6d2b2014 used=227758893
20171002-120019-351 0000 001752 INF mem: addMem(193164080): mem-titledb. ptr=0x7f3e616bf014 used=585550373
20171002-120022-794 0000 001752 INF mem: addMem(100000022): mem-spiderdb. ptr=0x7f3e4e920014 used=994927031
20171002-120023-993 0000 001752 INF spider: nuking Doledb periodically is enabled, interval = 86400 seconds
20171002-120026-170 0000 001752 DBG Cleaning up any unfinished merges of main posdb
20171002-120026-171 0000 001752 DBG Found 0 .dat files for posdb
20171002-120026-171 0000 001752 DBG Found 0 .dat files for posdb in merge-space
20171002-120026-171 0000 001752 DBG Cleaned up any unfinished merges of main posdb
20171002-120026-171 0000 001752 INF db: Generating global index for posdb
20171002-120026-269 0000 001752 DBG Cleaning up any unfinished merges of main titledb
20171002-120026-270 0000 001752 DBG Found 0 .dat files for titledb
20171002-120026-270 0000 001752 DBG Found 0 .dat files for titledb in merge-space
20171002-120026-270 0000 001752 DBG Cleaned up any unfinished merges of main titledb
20171002-120026-360 0000 001752 DBG Cleaning up any unfinished merges of main tagdb
20171002-120026-360 0000 001752 DBG Found 0 .dat files for tagdb
20171002-120026-361 0000 001752 DBG Found 0 .dat files for tagdb in merge-space
20171002-120026-361 0000 001752 DBG Cleaned up any unfinished merges of main tagdb
20171002-120026-428 0000 001752 DBG Cleaning up any unfinished merges of main clusterdb
20171002-120026-429 0000 001752 DBG Found 0 .dat files for clusterdb
20171002-120026-429 0000 001752 DBG Found 0 .dat files for clusterdb in merge-space
20171002-120026-429 0000 001752 DBG Cleaned up any unfinished merges of main clusterdb
20171002-120026-483 0000 001752 DBG Cleaning up any unfinished merges of main linkdb
20171002-120026-483 0000 001752 DBG Found 0 .dat files for linkdb
20171002-120026-483 0000 001752 DBG Found 0 .dat files for linkdb in merge-space
20171002-120026-483 0000 001752 DBG Cleaned up any unfinished merges of main linkdb
20171002-120026-586 0000 001752 DBG Cleaning up any unfinished merges of main spiderdb
20171002-120026-586 0000 001752 DBG Found 0 .dat files for spiderdb
20171002-120026-587 0000 001752 DBG Found 0 .dat files for spiderdb in merge-space
20171002-120026-587 0000 001752 DBG Cleaned up any unfinished merges of main spiderdb
20171002-120026-640 0000 001752 DBG Cleaning up any unfinished merges of main doledb
20171002-120026-640 0000 001752 DBG Found 0 .dat files for doledb
20171002-120026-651 0000 001752 DBG Found 0 .dat files for doledb in merge-space
20171002-120026-652 0000 001752 DBG Cleaned up any unfinished merges of main doledb
20171002-120026-662 0000 001752 DBG Loading high_frequency_term_posdb_shortcuts.dat
20171002-120026-672 0000 001752 INF Couldn't open high_frequency_term_posdb_shortcuts.dat, errno=2 (No such file or directory)
20171002-120026-682 0000 001752 DBG Loading page_temperatures.dat
20171002-120026-682 0000 001752 INF Couldn't open page_temperatures.dat, errno=2 (No such file or directory)
20171002-120026-682 0000 001752 DBG Loading docid2flagsandsitemap.dat
20171002-120026-682 0000 001752 INF Couldn't open docid2flagsandsitemap.dat, errno=2 (No such file or directory)
20171002-120026-682 0000 001752 INF Initializing DnsBlockList with dnsblocklist.txt
20171002-120026-689 0000 001752 INF DnsBlockList::load: Unable to stat dnsblocklist.txt
20171002-120026-699 0000 001752 INF Initializing UrlMatchList with urlblacklist.txt
20171002-120026-700 0000 001752 INF UrlMatchList::load: Unable to stat urlblacklist.txt
20171002-120026-700 0000 001752 INF Initializing UrlMatchList with urlwhitelist.txt
20171002-120026-700 0000 001752 INF UrlMatchList::load: Unable to stat urlwhitelist.txt
20171002-120026-700 0000 001752 INF Initializing RobotsCheckList with robotschecklist.txt
20171002-120026-700 0000 001752 INF RobotsCheckList::load: Unable to stat robotschecklist.txt
20171002-120026-734 0000 001752 INF disk: call to open(/home/memetb/open-source-search-engine/coll.main.0/tmpfile) blocked for 16 ms.
20171002-120028-023 0000 001752 INF mem: addMem(109051904): udictht. ptr=0x7f3e3426c014 used=1413547359
20171002-120030-978 0000 001752 DBG table: grewtable udictht from 2097152 to 8388608 slots in 2721 ms (this=0x113cbe0) (used=0)
20171002-120032-212 0000 001752 DBG gb: unifiedDict-buf.txt or unifiedDict-map.dat checksum is not approved for live service (1974148069587949864 != -14450509118443930)
20171002-120032-614 0000 001752 INF mem: addMem(102564000): UdpServer. ptr=0x7f3e2e09b014 used=1508752745
20171002-120032-757 0000 001752 INI udp: Listening on UDP port 9000 with fd=5.
20171002-120032-919 0000 001752 INI udp: Listening on UDP port 5998 with fd=6.
20171002-120032-920 0000 001752 INI dns: Sending requests on client port 5998
20171002-120032-920 0000 001752 INI dns: Using nameserver 8.8.8.8:53.
20171002-120032-920 0000 001752 INI dns: Using nameserver 8.8.4.4:53.
20171002-120032-980 0000 001752 INF dns: Initializing library
20171002-120033-009 0000 001752 INF dns: Initializing settings
20171002-120033-328 0000 001752 INF https: Reading SSL certificate from: /home/memetb/open-source-search-engine/gb.pem
20171002-120033-355 0000 001752 INI http: Listening on TCP port 8000 with sd=7
20171002-120033-355 0000 001752 INI https: Listening on TCP port 7000 with sd=8
20171002-120033-536 0000 001752 ERR Unknown command: '0'
Failed to start gb. Exiting.
gb: GbMutex.cpp:18: GbMutex::~GbMutex(): Assertion `rc==0' failed.
İptal edildi (çekirdek döküldü) -> ( Canceled (kernel core) )
memetb@memetb:~/open-source-search-engine$

I want help with this issue

**Comment by ghost** [comment]
Workaround implemented in commit 07e17d6b247bf55359e0fa96b8465e2f9aea7c84

**Comment by mehmet-biter** [comment]
memetb@memetb:~/open-source-search-engine$ make -j4
g++ -D_REENTRANT_ -I. -Ithird-party/compact_enc_det -Ithird-party/c-ares -Ithird-party/sparsepp -DDEBUG_MUTEXES -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wno-invalid-offsetof -Wno-unused-result -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -DGIT_COMMIT_ID=4bd1ecf25a397356022994941354428a841b1240-dirty -DGIT_BRANCH=master -DBUILD_CONFIG=release -c Version.cpp
g++ -D_REENTRANT_ -I. -Ithird-party/compact_enc_det -Ithird-party/c-ares -Ithird-party/sparsepp -DDEBUG_MUTEXES -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wno-invalid-offsetof -Wno-unused-result -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -o gb main.o Abbreviations.o AdultCheck.o BigFile.o Clusterdb.o Collectiondb.o Conf.o CountryCode.o DailyMerge.o Dir.o Dns.o Domains.o Errno.o Entities.o File.o GbMutex.o HashTable.o HighFrequencyTermShortcuts.o PageTemperatureRegistry.o Docid2Siteflags.o HttpMime.o HttpRequest.o HttpServer.o Hostdb.o iana_charset.o Images.o ip.o JobScheduler.o Json.o Lang.o Log.o Mem.o Msg0.o Msg4In.o Msg4Out.o MsgC.o Msg13.o Msg20.o Msg22.o Msg39.o Msg3a.o Msg51.o Msge0.o Msge1.o Multicast.o Parms.o Pages.o PageAddColl.o PageAddUrl.o PageBasic.o PageCrawlBot.o PageGet.o PageHealthCheck.o PageHosts.o PageInject.o PageParser.o PagePerf.o PageReindex.o PageResults.o PageRoot.o PageSockets.o PageStats.o PageThreads.o PageTitledb.o PageSpiderdbLookup.o PageSpider.o PageDoledbIPTable.o Phrases.o HostFlags.o Process.o Proxy.o Punycode.o InstanceInfoExchange.o Query.o RdbCache.o RdbDump.o RdbMem.o RdbMerge.o RdbScan.o RdbTree.o Rebalance.o Repair.o RobotRule.o Robots.o Sanity.o ScalingFunctions.o SearchInput.o SiteGetter.o Speller.o SpiderProxy.o Stats.o SummaryCache.o Synonyms.o Tagdb.o TcpServer.o Titledb.o Version.o Wiki.o Wiktionary.o UdpSlot.o Url.o   Bits.o Doledb.o fctypes.o hash.o HashTableT.o HashTableX.o Highlight.o linkspam.o Loop.o Matches.o matches2.o Msg2.o Msg3.o Msg5.o Pops.o Pos.o Posdb.o PosdbTable.o Profiler.o Rdb.o RdbBase.o Sections.o Spider.o SpiderCache.o SpiderColl.o SpiderLoop.o StopWords.o Summary.o Title.o UCPropTable.o UdpServer.o Unicode.o UnicodeProperties.o Words.o Xml.o XmlDoc.o XmlDoc_Indexing.o XmlNode.o  DocDelete.o DnsBlockList.o IPAddressChecks.o Linkdb.o Msg40.o Msg25.o RdbBuckets.o RdbIndex.o RdbIndexQuery.o RdbList.o RdbMap.o RobotsCheckList.o SafeBuf.o sort.o SpiderdbHostDelete.o Statistics.o ScoringWeights.o TopTree.o UrlMatch.o UrlMatchList.o UrlMatchHostList.o UrlBlockCheck.o UrlComponent.o UrlParser.o UdpStatistic.o UrlRealtimeClassification.o WantedChecker.o MergeSpaceCoordinator.o GbMoveFile.o GbMoveFile2.o GbCopyFile.o GbMakePath.o GbUtil.o GbSignature.o GbCompress.o GbRegex.o GbThreadQueue.o GbEncoding.o GbLanguage.o GbDns.o  -lm -lpthread -lssl -lcrypto -lz -lpcre -ldl ./libiconv64.a -Wl,-rpath=. -L. -lcld2_full -lcld3 -lprotobuf -lced -lcares
memetb@memetb:~/open-source-search-engine$ make dist
g++ -D_REENTRANT_ -I. -Ithird-party/compact_enc_det -Ithird-party/c-ares -Ithird-party/sparsepp -DDEBUG_MUTEXES -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wno-invalid-offsetof -Wno-unused-result -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -DGIT_COMMIT_ID=4bd1ecf25a397356022994941354428a841b1240-dirty -DGIT_BRANCH=master -DBUILD_CONFIG=release -c Version.cpp
g++ -D_REENTRANT_ -I. -Ithird-party/compact_enc_det -Ithird-party/c-ares -Ithird-party/sparsepp -DDEBUG_MUTEXES -g -fno-stack-protector -DPTHREADS -std=c++11 -march=core-avx-i -msse4.2  -MMD -MP -Wall -Wformat-security -Wodr -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wno-invalid-offsetof -Wno-unused-result -Wstrict-aliasing=0 -Wno-write-strings -Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -o gb main.o Abbreviations.o AdultCheck.o BigFile.o Clusterdb.o Collectiondb.o Conf.o CountryCode.o DailyMerge.o Dir.o Dns.o Domains.o Errno.o Entities.o File.o GbMutex.o HashTable.o HighFrequencyTermShortcuts.o PageTemperatureRegistry.o Docid2Siteflags.o HttpMime.o HttpRequest.o HttpServer.o Hostdb.o iana_charset.o Images.o ip.o JobScheduler.o Json.o Lang.o Log.o Mem.o Msg0.o Msg4In.o Msg4Out.o MsgC.o Msg13.o Msg20.o Msg22.o Msg39.o Msg3a.o Msg51.o Msge0.o Msge1.o Multicast.o Parms.o Pages.o PageAddColl.o PageAddUrl.o PageBasic.o PageCrawlBot.o PageGet.o PageHealthCheck.o PageHosts.o PageInject.o PageParser.o PagePerf.o PageReindex.o PageResults.o PageRoot.o PageSockets.o PageStats.o PageThreads.o PageTitledb.o PageSpiderdbLookup.o PageSpider.o PageDoledbIPTable.o Phrases.o HostFlags.o Process.o Proxy.o Punycode.o InstanceInfoExchange.o Query.o RdbCache.o RdbDump.o RdbMem.o RdbMerge.o RdbScan.o RdbTree.o Rebalance.o Repair.o RobotRule.o Robots.o Sanity.o ScalingFunctions.o SearchInput.o SiteGetter.o Speller.o SpiderProxy.o Stats.o SummaryCache.o Synonyms.o Tagdb.o TcpServer.o Titledb.o Version.o Wiki.o Wiktionary.o UdpSlot.o Url.o   Bits.o Doledb.o fctypes.o hash.o HashTableT.o HashTableX.o Highlight.o linkspam.o Loop.o Matches.o matches2.o Msg2.o Msg3.o Msg5.o Pops.o Pos.o Posdb.o PosdbTable.o Profiler.o Rdb.o RdbBase.o Sections.o Spider.o SpiderCache.o SpiderColl.o SpiderLoop.o StopWords.o Summary.o Title.o UCPropTable.o UdpServer.o Unicode.o UnicodeProperties.o Words.o Xml.o XmlDoc.o XmlDoc_Indexing.o XmlNode.o  DocDelete.o DnsBlockList.o IPAddressChecks.o Linkdb.o Msg40.o Msg25.o RdbBuckets.o RdbIndex.o RdbIndexQuery.o RdbList.o RdbMap.o RobotsCheckList.o SafeBuf.o sort.o SpiderdbHostDelete.o Statistics.o ScoringWeights.o TopTree.o UrlMatch.o UrlMatchList.o UrlMatchHostList.o UrlBlockCheck.o UrlComponent.o UrlParser.o UdpStatistic.o UrlRealtimeClassification.o WantedChecker.o MergeSpaceCoordinator.o GbMoveFile.o GbMoveFile2.o GbCopyFile.o GbMakePath.o GbUtil.o GbSignature.o GbCompress.o GbRegex.o GbThreadQueue.o GbEncoding.o GbLanguage.o GbDns.o  -lm -lpthread -lssl -lcrypto -lz -lpcre -ldl ./libiconv64.a -Wl,-rpath=. -L. -lcld2_full -lcld3 -lprotobuf -lced -lcares
gb-20171002-4bd1ecf/
gb-20171002-4bd1ecf/libpng12.so.0
gb-20171002-4bd1ecf/gbstart.sh
gb-20171002-4bd1ecf/LICENSE
gb-20171002-4bd1ecf/jpegtopnm
gb-20171002-4bd1ecf/mysynonyms.txt
gb-20171002-4bd1ecf/pnmscale
gb-20171002-4bd1ecf/ucdata/
gb-20171002-4bd1ecf/ucdata/kd_data.dat
gb-20171002-4bd1ecf/ucdata/kdmap.dat
gb-20171002-4bd1ecf/ucdata/properties.dat
gb-20171002-4bd1ecf/ucdata/uppermap.dat
gb-20171002-4bd1ecf/ucdata/lowermap.dat
gb-20171002-4bd1ecf/ucdata/scripts.dat
gb-20171002-4bd1ecf/libjpeg.so.62
gb-20171002-4bd1ecf/gb
gb-20171002-4bd1ecf/LICENSE-3RD-PARTY-CLD2
gb-20171002-4bd1ecf/gb.pem
gb-20171002-4bd1ecf/libtiff.so.4
gb-20171002-4bd1ecf/wiktionary-buf.txt
gb-20171002-4bd1ecf/libcld2_full.so
gb-20171002-4bd1ecf/libnetpbm.so.10
gb-20171002-4bd1ecf/gbconvert.sh
gb-20171002-4bd1ecf/valgrind.cfg
gb-20171002-4bd1ecf/html/
gb-20171002-4bd1ecf/html/gears.gif
gb-20171002-4bd1ecf/html/test.arc.gz
gb-20171002-4bd1ecf/html/favicon.ico
gb-20171002-4bd1ecf/html/hosts.conf.txt
gb-20171002-4bd1ecf/html/gigabits40.jpg
gb-20171002-4bd1ecf/html/developer.html
gb-20171002-4bd1ecf/html/gigablast.jpg
gb-20171002-4bd1ecf/html/adv.html
gb-20171002-4bd1ecf/html/facets40.jpg
gb-20171002-4bd1ecf/html/logo-small.png
gb-20171002-4bd1ecf/html/rocket.jpg
gb-20171002-4bd1ecf/html/magglass.png
gb-20171002-4bd1ecf/html/test.warc.gz
gb-20171002-4bd1ecf/html/robots.txt
gb-20171002-4bd1ecf/html/faq.html
gb-20171002-4bd1ecf/html/robot3.png
gb-20171002-4bd1ecf/html/terms.html
gb-20171002-4bd1ecf/html/gb.conf.txt
gb-20171002-4bd1ecf/antiword
gb-20171002-4bd1ecf/LICENSE-3RD-PARTY-SLACKTEE
gb-20171002-4bd1ecf/sitelinks.txt
gb-20171002-4bd1ecf/antiword-dir/
gb-20171002-4bd1ecf/antiword-dir/koi8-u.txt
gb-20171002-4bd1ecf/antiword-dir/cp852.txt
gb-20171002-4bd1ecf/antiword-dir/8859-15.txt
gb-20171002-4bd1ecf/antiword-dir/8859-14.txt
gb-20171002-4bd1ecf/antiword-dir/8859-8.txt
gb-20171002-4bd1ecf/antiword-dir/roman.txt
gb-20171002-4bd1ecf/antiword-dir/8859-4.txt
gb-20171002-4bd1ecf/antiword-dir/fontnames
gb-20171002-4bd1ecf/antiword-dir/koi8-r.txt
gb-20171002-4bd1ecf/antiword-dir/8859-7.txt
gb-20171002-4bd1ecf/antiword-dir/8859-6.txt
gb-20171002-4bd1ecf/antiword-dir/MacRoman.txt
gb-20171002-4bd1ecf/antiword-dir/8859-10.txt
gb-20171002-4bd1ecf/antiword-dir/8859-13.txt
gb-20171002-4bd1ecf/antiword-dir/cp437.txt
gb-20171002-4bd1ecf/antiword-dir/Example
gb-20171002-4bd1ecf/antiword-dir/UTF-8.txt
gb-20171002-4bd1ecf/antiword-dir/Unicode
gb-20171002-4bd1ecf/antiword-dir/fontnames.russian
gb-20171002-4bd1ecf/antiword-dir/cp850.txt
gb-20171002-4bd1ecf/antiword-dir/8859-5.txt
gb-20171002-4bd1ecf/antiword-dir/cp1250.txt
gb-20171002-4bd1ecf/antiword-dir/8859-3.txt
gb-20171002-4bd1ecf/antiword-dir/cp1252.txt
gb-20171002-4bd1ecf/antiword-dir/Default
gb-20171002-4bd1ecf/antiword-dir/8859-9.txt
gb-20171002-4bd1ecf/antiword-dir/8859-1.txt
gb-20171002-4bd1ecf/antiword-dir/8859-16.txt
gb-20171002-4bd1ecf/antiword-dir/cp1251.txt
gb-20171002-4bd1ecf/antiword-dir/8859-2.txt
gb-20171002-4bd1ecf/giftopnm
gb-20171002-4bd1ecf/pngtopnm
gb-20171002-4bd1ecf/wikititles.txt.part1
gb-20171002-4bd1ecf/wiktionary-syns.dat
gb-20171002-4bd1ecf/bmptopnm
gb-20171002-4bd1ecf/wiktionary-lang.txt
gb-20171002-4bd1ecf/wikititles.txt.part2
gb-20171002-4bd1ecf/ppmtojpeg
gb-20171002-4bd1ecf/.valgrindrc
gb-20171002-4bd1ecf/tifftopnm
gb-20171002-4bd1ecf/pstotext
gb-20171002-4bd1ecf/unifiedDict.txt
memetb@memetb:~/open-source-search-engine$ ./gb 0
20171002-164837-850 0000 001860 INI conf: Gigablast Version      : Oct  2 2017 19:47:30
20171002-164837-850 0000 001860 INI conf: Gigablast Architecture : 64-bit
20171002-164837-850 0000 001860 INI conf: Gigablast Build config : release
20171002-164837-850 0000 001860 INI conf: Gigablast Git commit   : 4bd1ecf25a397356022994941354428a841b1240-dirty
20171002-164837-850 0000 001860 DBG host: Working directory is /home/memetb/open-source-search-engine/
20171002-164837-850 0000 001860 DBG host: Using /home/memetb/open-source-search-engine/hosts.conf
20171002-164837-850 0000 001860 DBG host: Process ID is 1859
20171002-164837-850 0000 001860 DBG host: Detected local ip 127.0.0.1
20171002-164837-851 0000 001860 DBG host: Detected local ip 192.168.1.37
20171002-164837-851 0000 001860 DBG host: Running as host id #0
20171002-164837-894 0000 001860 INF wikt: Loading /home/memetb/open-source-search-engine/wiktionary-syns.dat
20171002-164838-448 0000 001860 INF wikt: Loading /home/memetb/open-source-search-engine/wiktionary-buf.txt
20171002-164838-803 0000 001860 DBG wikt: test "love" -> "en|love,loved,loving,loves"
20171002-164838-803 0000 001860 INF wiki: Loading /home/memetb/open-source-search-engine/wikititles2.dat
20171002-164838-840 0000 001860 INF mem: addMem(100663296): tbl-wiki. ptr=0x7fc0ef859014 used=126978143
20171002-164839-650 0000 001860 INF db: Loading conf for collection main (0)
20171002-164839-675 0000 001860 DBG table: grewtable enttbl from 4096 to 8192 slots in 0 ms (this=0x9d85a0) (used=2048)
20171002-164839-687 0000 001860 INF mem: addMem(349879400): buckets-posdb. ptr=0x7fc0da2ac014 used=227758893
20171002-164839-691 0000 001860 INF mem: addMem(193164080): mem-titledb. ptr=0x7fc0cea74014 used=585550373
20171002-164841-885 0000 001860 INF mem: addMem(100000022): mem-spiderdb. ptr=0x7fc0bbcd5014 used=994927031
20171002-164841-952 0000 001860 INF spider: nuking Doledb periodically is enabled, interval = 86400 seconds
20171002-164844-734 0000 001860 DBG Cleaning up any unfinished merges of main posdb
20171002-164844-734 0000 001860 DBG Found 0 .dat files for posdb
20171002-164844-735 0000 001860 DBG Found 0 .dat files for posdb in merge-space
20171002-164844-736 0000 001860 DBG Cleaned up any unfinished merges of main posdb
20171002-164844-736 0000 001860 INF db: Generating global index for posdb
20171002-164844-795 0000 001860 DBG Cleaning up any unfinished merges of main titledb
20171002-164844-796 0000 001860 DBG Found 0 .dat files for titledb
20171002-164844-796 0000 001860 DBG Found 0 .dat files for titledb in merge-space
20171002-164844-796 0000 001860 DBG Cleaned up any unfinished merges of main titledb
20171002-164844-823 0000 001860 DBG Cleaning up any unfinished merges of main tagdb
20171002-164844-823 0000 001860 DBG Found 0 .dat files for tagdb
20171002-164844-823 0000 001860 DBG Found 0 .dat files for tagdb in merge-space
20171002-164844-823 0000 001860 DBG Cleaned up any unfinished merges of main tagdb
20171002-164844-861 0000 001860 DBG Cleaning up any unfinished merges of main clusterdb
20171002-164844-862 0000 001860 DBG Found 0 .dat files for clusterdb
20171002-164844-862 0000 001860 DBG Found 0 .dat files for clusterdb in merge-space
20171002-164844-862 0000 001860 DBG Cleaned up any unfinished merges of main clusterdb
20171002-164844-902 0000 001860 DBG Cleaning up any unfinished merges of main linkdb
20171002-164844-903 0000 001860 DBG Found 0 .dat files for linkdb
20171002-164844-903 0000 001860 DBG Found 0 .dat files for linkdb in merge-space
20171002-164844-903 0000 001860 DBG Cleaned up any unfinished merges of main linkdb
20171002-164844-949 0000 001860 DBG Cleaning up any unfinished merges of main spiderdb
20171002-164844-949 0000 001860 DBG Found 0 .dat files for spiderdb
20171002-164844-950 0000 001860 DBG Found 0 .dat files for spiderdb in merge-space
20171002-164844-950 0000 001860 DBG Cleaned up any unfinished merges of main spiderdb
20171002-164844-958 0000 001860 DBG Cleaning up any unfinished merges of main doledb
20171002-164844-958 0000 001860 DBG Found 0 .dat files for doledb
20171002-164844-963 0000 001860 DBG Found 0 .dat files for doledb in merge-space
20171002-164844-963 0000 001860 DBG Cleaned up any unfinished merges of main doledb
20171002-164844-993 0000 001860 DBG Loading high_frequency_term_posdb_shortcuts.dat
20171002-164845-001 0000 001860 INF Couldn't open high_frequency_term_posdb_shortcuts.dat, errno=2 (No such file or directory)
20171002-164845-001 0000 001860 DBG Loading page_temperatures.dat
20171002-164845-001 0000 001860 INF Couldn't open page_temperatures.dat, errno=2 (No such file or directory)
20171002-164845-001 0000 001860 DBG Loading docid2flagsandsitemap.dat
20171002-164845-002 0000 001860 INF Couldn't open docid2flagsandsitemap.dat, errno=2 (No such file or directory)
20171002-164845-002 0000 001860 INF Initializing DnsBlockList with dnsblocklist.txt
20171002-164845-002 0000 001860 INF DnsBlockList::load: Unable to stat dnsblocklist.txt
20171002-164845-013 0000 001860 INF Initializing UrlMatchList with urlblacklist.txt
20171002-164845-013 0000 001860 INF UrlMatchList::load: Unable to stat urlblacklist.txt
20171002-164845-013 0000 001860 INF Initializing UrlMatchList with urlwhitelist.txt
20171002-164845-014 0000 001860 INF UrlMatchList::load: Unable to stat urlwhitelist.txt
20171002-164845-014 0000 001860 INF Initializing RobotsCheckList with robotschecklist.txt
20171002-164845-014 0000 001860 INF RobotsCheckList::load: Unable to stat robotschecklist.txt
20171002-164845-037 0000 001860 INF disk: call to open(/home/memetb/open-source-search-engine/coll.main.0/tmpfile) blocked for 2 ms.
20171002-164845-606 0000 001860 INF mem: addMem(109051904): udictht. ptr=0x7fc0a1621014 used=1413547359
20171002-164845-653 0000 001860 DBG table: grewtable udictht from 2097152 to 8388608 slots in 47 ms (this=0x113cbe0) (used=0)
20171002-164846-656 0000 001860 DBG gb: unifiedDict-buf.txt or unifiedDict-map.dat checksum is not approved for live service (1974148069587949864 != -14450509118443930)
20171002-164846-895 0000 001860 INF mem: addMem(102564000): UdpServer. ptr=0x7fc09b450014 used=1508752745
20171002-164847-483 0000 001860 INI udp: Listening on UDP port 9000 with fd=5.
20171002-164847-641 0000 001860 INI udp: Listening on UDP port 5998 with fd=6.
20171002-164847-642 0000 001860 INI dns: Sending requests on client port 5998
20171002-164847-642 0000 001860 INI dns: Using nameserver 8.8.8.8:53.
20171002-164847-642 0000 001860 INI dns: Using nameserver 8.8.4.4:53.
20171002-164847-699 0000 001860 INF dns: Initializing library
20171002-164847-749 0000 001860 INF dns: Initializing settings
20171002-164848-086 0000 001860 INF https: Reading SSL certificate from: /home/memetb/open-source-search-engine/gb.pem
20171002-164848-113 0000 001860 INI http: Listening on TCP port 8000 with sd=7
20171002-164848-113 0000 001860 INI https: Listening on TCP port 7000 with sd=8
20171002-164848-202 0000 001860 ERR Unknown command: '0'
error

**Comment by ghost** [comment]
"./gb 0" has earlier started the local instance. The "0" was ignored.
This is no longer ignored but detected as an unsupported command.

If you want to operate on specific instances then use supported command formats (eg. "gb start 0")
