### ISSUE TITLE
Could not connect to url classification services

### ISSUE THREAD

**Issue by arpadlukacs** [privacore/open-source-search-engine#39]
I have this error in the log and I see there are settings related to this service, but I can't seem to figure out what service should I need to connect here and I do not see any related installation instruction neither.

**Comment by kjin9174** [comment]
I have same error. BUt i didn't solve this. did you solve?

**Comment by arpadlukacs** [comment]
No, not yet. I guess this error prevents the crawler to collect URLs. I have few URLs, but nothing happened so far.

**Comment by br-privacore** [comment]
This is not a fatal error. The URL Classification Server is a module you must develop yourself. It can analyze if a URL is malicious, e.g. by using Google's SafeSearch API (or any other heurestics you choose to implement). It is used (if configured) when handling queries. If it cannot connect, it is simply not used.

It has nothing to do with spidering not running.

**Comment by arpadlukacs** [comment]
Ok, thank you.
