### ISSUE TITLE
Procedure to start FindX (Gigablast) for clustering?

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#43]
Hello,

I looking over the code, I can see that the FindX team has done an amazing amount of work to refine the older Gigablast code which is awesome.

I was able to compile the code on my Ubuntu 16.04 with no problems and am not looking for the documentation to start up "gb" in single instance mode as well as in cluster mode as it seems to have clustering capabilities.

Also, what browser port do I access the admin and interface after it is started? Are these the same as the original Gigablast?

Thanks again,
Lonnie

**Comment by br-privacore** [comment]
It is the same as the original Gigablast.

**Comment by Outstep** [comment]
Thanks again Brian,

I'll try to dig that up on the Gigablast site but did not see anything
related to cluster startup.

Would you be willing to tell me the steps for that?

Thanks,
Lonnie

**Comment by br-privacore** [comment]
Look at the comments in the hosts.conf file.

I must be up front and say that our aim is not to produce how-to documentation and operational support. We adjust the documentation as we move along, but realistically, you will have to be able to dig into the code yourself.

**Comment by Outstep** [comment]
Thanks again.
