### ISSUE TITLE
Clarification on FindX Code

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#47]
Hello All,

I have been digging in the code as well as have compiled it up but need some clarification.

This code does not actually compile to to give the same Web-Interface as the FindX website and is just the driving backend, correct?

It seems that have a Gigablast repository (this one) and somewhere else is your FindX repository that is not open to the public. Is this fair to say?

Thanks,
Lonnie

**Comment by br-privacore** [comment]
Hi Lonnie,

you are correct. For now we open source the backend and have the frontend as closed source. In a few months I expect we have open sourced the instant answers plugins for the frontend, but there are no current plans to open source the frontend code itself.

**Comment by Outstep** [comment]
Hi Brian,

Thanks for the clarification.

I would be interested to know what open source JS code used for the "images" layout sections as I might have a small use for something like that in the project that I am working on now.

Cheers,
Lonnie

**Comment by br-privacore** [comment]
It is custom made.
