### ISSUE TITLE
Docker setup underway

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#48]
Hello, 

I am currently in the process of trying to setup a Docker container dockerfile for the FindX (Gigablast) code since it seems that there are significant improvements in you FindX version over the older Gigablast version.

My hope is that even though the internals of the newer findx code may differ from the older original code, but the functionality is the same (in particular when it comes to the clustering capability that the original Gigablast code has).

As far as creating the dockerfile, I would like to know if there has already been some work in this area?

If not, then I would like to try and get an idea as to what directories may need to be passed to the host as the idea is to have the data, and configs, stored on the host and mainly the binaries running in the docker container.

Any assistance would be greatly appreciated.
Thanks,
Lonnie

**Comment by br-privacore** [comment]
No work done.

You really need to familiarize yourself with the code and files as we have not documented much compared to the original gigablast project. Data files are primarily written to coll.* folders, but also to the root folder (like *-saved.dat and conf files, but also log files etc.)
