### ISSUE TITLE
confirming original API still works?

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#49]
Hello,

I know that your team has made significant changes to the original Gigablast code-base, but I wanted to confirm that the original API is still intact and functional?

In particular, I am interested in the API call:

/ADDURL 

so that I can send URL's to the FindX backend?

Also, is there a way to send a BLOCK of URL's to the backend.

On a side thought, I was wondering that if the /ADDURL is active then does this not make a security vulnerability for an attack surface that would allow someone to sends thousands or more same URL to the /ADDURL call?  

Or, does FindX (Gigablast) disregard duplicate URL's not activate spiders on the same URL?

Just wondering on this.

Cheers,
Lonnie

**Comment by br-privacore** [comment]
I urge you try familiarize yourself with our fork and which features are left in it. We are continuing to strip out features we have no use for, to simplify the codebase for our use. 

"Add URL" is still present, and yes, somebody can submit thousands of requests. The duplicates are filtered out by the spidering process.
