### ISSUE TITLE
confirming OSSE functionality

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#50]
Hello,

As I am getting more familiar with the source code and functionality, I wanted to confirm that the FindX modified OSSE (Open Source Search Engine) on GitHub is no exactly the same being used by the FindX site?

Actually, I know that the web page templates are closed source, but in compiling up and running the OSSE instance, it seems that the categories code is not available as well.

The FindX site uses:

WEB -------------
https://www.findx.com/web?q=mars

IMAGES ---------
https://www.findx.com/images?q=mars

VIDEO --------
https://www.findx.com/video?q=mars

And the release OSSE code does not seem to support various "searchtypes" like (web, images, videos) since the original Gigablast OSSE release did not include this code as well. 

I wanted to confirm that it is not included in the FindX fork as well, just for clarification. 

And yes, I have been familiarizing myself with the source code, to be clear.
Thanks again,
Lonnie

**Comment by br-privacore** [comment]
Our fork of Gigablast powers the web search of Findx. The rest as you mention, is not part of this and never has been part of Gigablast.

**Comment by Outstep** [comment]
Thanks for getting back to me.  Actually,  Matt Wells says that those parts
within the full Gigablast code are closed source and not given out in the
open source version. Regards.

**Comment by br-privacore** [comment]
He may have added it to the original Gigablast, I don't know. We have developed what we use ourselves, and we do not get updates from Matt Wells. As you know, his repository has been stale for ages. We have no contact with him.
