### ISSUE TITLE
Search exit: Ecosia

### ISSUE THREAD

**Issue by grahamperrin** [privacore/open-source-search-engine#51]
Maybe add [Ecosia](https://www.ecosia.org/) as a search exit? 

[Where do Ecosia's search results come from? – Ecosia Knowledge Base](https://ecosia.zendesk.com/hc/en-us/articles/206153381-Where-do-Ecosia-s-search-results-come-from-) – there's the relationship with Bing … if I'm to exit Findx in a Bing direction, I'd like the exit to primarily do some good through Ecosia.

**Comment by brianschildt** [comment]
Thanks for the idea - that should be doable.  Will add it to [the list of search exits](https://help.findx.com/en/search-exits#search). @br-privacore  - keeping this issue open until done?

**Comment by grahamperrin** [comment]
Thanks!

**Comment by grahamperrin** [comment]
Apologies for bumping … not chasing, just wondering when this might happen. 

TIA
