### ISSUE TITLE
A question of data storage location?

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#52]
Hello,

I have been playing around with FindX and GigaBlast for a bit now, and am still trying to determine if it is viable for a project that I am working on. It is certainly very fast and I like that part, but part of what I am doing is to see if I can get FindX (Gigablast) to run in a Docker container.

I have found out that Gigablast, places many data files in the application root directory and I am trying to determine if FindX does the same as an optimal solution would be to put all of the data files and databases down a "./data" directory then the docker container can just export that working directory to the host.

So then, that is my fundamental question.

Does FindX put its files, or can it easily be made to put the data/database files down a working directory?

This is not an easy task to do with Gigablast, but I am hopeful that FindX will have a better solution.

Thanks,
Lonnie

**Comment by br-privacore** [comment]
Hi,

we have not changed this, so our fork also stores data files in the application folder, and it does require some work to change that.

**Comment by Outstep** [comment]
Thanks for the information, Brian.

I was suspecting that was the case.

No worries as I guess that we will just have to start digging into the code
to work on it.
Cheer :)

**Comment by br-privacore** [comment]
Yeah, we have no current plans to do it on the short term. There are quite a few files, both configuration files, blocklists, current state (-saved.dat) files, log files, some new info-sites appended to during spidering etc.

**Comment by Outstep** [comment]
Well, if we go forward with the FindX fork, which I must say that you have
really cleaned up and improved on the Gigablast code, and make these
changes then I'll let you know and perhaps can send you over a copy.

Cheers,Lonnie

**Comment by br-privacore** [comment]
Please do, all contributions are welcome.

PS. Remember many files are licensed under AGPL, which requires publishing of changes.

**Comment by martinvahi** [comment]
My "fix" to the problem would be to avoid changing 
anything in the code, create a "deployment fork" of the
upstream deliverables, test the deployment fork thoroughly 
WITHOUT DOING ANY CUSTOM MODIFICATIONS to the
deployment fork and then use only a clean copy of the
deployment fork by combining the UNMODIFIED upstream
copy, the deployment form, with WRAPPER SCRIPTS.

If the upstream/Privacore publishes new versions, then
those will NOT BE TAKEN TO USE AUTOMATICALLY, they will
be thoroughly tested and if the tests fail, then the new upstream
version is ignored, the next upstream version is also tested, and so forth,
until one of the upstream versions passes the tests. Meanwhile
only the old deployment fork is used at production. In this case, the
wrapper scripts can initialize the copy/instance of the deployment fork by
creating Linux file links from the 

    ./data
    to the
    <Gigablast default data folder>

The links may go from one mounted folder to another. There's probably
some nasty delays, if the folder is mounted over sshfs or some other
network mounting means, but the speeds can be tested/measured.
That way the virtual_machine/docker_container/some_lightweight_jail does not
have to contain the data files. The Bash script that starts the search
engine, may create the links and skip starting up the search engine
process, if the links are broken or the creation of the links fails.

Of course, this approach is very subjective and not for everyone.
My, very subjective, suitable-only-for-people-who-are-similar-enough-to-me,
"development methodology" is described at one of my blog posts at:

https://martin.softf1.com/g/yellow_soap_opera_blog/2015_10-the-best-that-i-know-of-version-of-software-development-methodology
[archival copy](https://martin.softf1.com/g/yellow_soap_opera_blog/2015_10-the-best-that-i-know-of-version-of-software-development-methodology)

Thank You for reading my comment.
Thank You for reading my blog.

**Comment by Outstep** [comment]
Hi Brian,

I have been able to setup a nice and simple pass-through docker container for FindX and it works very well for our needs.

Actually, it simple maps the FindX directory on the server into a container and runs it, but the executables and data are protected in the container so that you have all of the Docker functionality as well.  

Really, it is similar to a Linux Chroot environment but for containers.

If you would like the dockerfile for this then just let me know and I will be happy to give it to you.
Cheers, Lonnie

**Comment by br-privacore** [comment]
Hi Lonnie,

sure, I'd like to see it - it could come in handy for testing purposes.

Thanks,
Brian

**Comment by etlweather** [comment]
@lonnieOST Do you have this Dockerfile available somewhere? Maybe a Gist?
