### ISSUE TITLE
Classification Server & Language Server

### ISSUE THREAD

**Issue by romcio** [privacore/open-source-search-engine#53]
Hello,

I'd like to ask how to start Classification Server and  Language Server  ? 
I see in logs error connection to ports 8079, 8078 but don't have found how to starts that options.

Best 

Roman

**Comment by br-privacore** [comment]
Those modules are still in development, and for now kept private. They are not essential for running the search engine - it works fine without.

**Comment by martinvahi** [comment]
Easy for me to say, specially when I 
do not even know the Gigablast/Privacore source, but 
shouldn't text analysis be a totally separate project?

The main thing to keep in mind is that the meaning of text
depends on the context, which can be understood by
studying other texts. May be there should be some 
"book reading agent" that reads search engine cache 
in stead of books and then writes tags to texts. 
Tags might/should be agent specific, contain multiple fields
of which one of the fields is the agent instance ID. 
One agent/robot/bot/AI_server might classify a text about 
cats as "literature for children", other
might classify it as "Science fiction", third agent/bot might
tag it with a propaganda warning, etc. 

May be an interface to use different text analysis modules,
tagging bot API, might already exist, I do not know, but 
if it doesn't, then the creation of the tagging bot API might
make more sense than bot development. If the AI/linguistics people
do the bot development, then the search engine developers
can focus more on the details of getting the spidering and storing and
indexing and scraping and scaling parts to shine. What regards to 
scaling, then the RethinkDB has a nice auto-scaling capability.

https://youtu.be/cnpSi9qI02E?t=8m48s

**Comment by br-privacore** [comment]
It is not for text classification as such, it is for determining if a result should be ignored because the URL is on a malware blocklist for example.
