### ISSUE TITLE
vagus: got 11 alive hosts instead of 12

### ISSUE THREAD

**Issue by romcio** [privacore/open-source-search-engine#54]
Hello,

I'm testing privacore with 12 node on same server (24 core server) and got after few minutes on one node, always the same node error:  ERR addr2line -e ./gb 0x55acd7316722  . All nodes have same configuration. 
How can solve that issue ? 

Best
 
Roman

**Comment by br-privacore** [comment]
You should run a debug build and provide full backtrace. I assume you are testing the master branch?
