### ISSUE TITLE
ERR found: Whats should it find on port 8078?

### ISSUE THREAD

**Issue by Outstep** [privacore/open-source-search-engine#55]
Hello, I am getting an error on the console:

20180518-134926-527 0000 019441 ERR client(query language): Could not connect to server(localhost:8078), most recent errno=111 (Connection refused)

Can you please tell me what the search engine should be finding on Port:8078

I just let the new dist generate the "host.conf" and then fixed the IP to the VPS server.

Thanks

**Comment by Outstep** [comment]
Hello,

I just found some information related to these ports 8078 & 8079

https://github.com/privacore/open-source-search-engine/issues/53

How can I disable them on the command line?

Thanks

**Comment by br-privacore** [comment]
upgrade to newest master where they are disabled by default

**Comment by Outstep** [comment]
thanks, I will give it a try.
