### ISSUE TITLE
Findx by Privacore not found amongst search tools at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [privacore/open-source-search-engine#56]
## Issue

about:preferences#search 

1. leads to https://addons.mozilla.org/en-GB/firefox/search-engines/ (or a localised equivalent)
2. then, for example, https://addons.mozilla.org/search/?q=Findx&type=search returns twenty results: 

- including [Findx](https://addons.mozilla.org/addon/find-x/) by _Anonymous user b88651_
- **excluding** [Findx](https://addons.mozilla.org/addon/findx/) by _Privacore_. 

### Observations

I was confused about the origins of what was found, because a few weeks ago I recalled finding something that was apparently official. 

A GitHub search of the Privacore organisation led me to https://github.com/privacore/open-source-search-engine/issues/35#issuecomment-331700027 and the required extension. 

Then I realised, https://addons.mozilla.org/search/?q=Findx&type=extension

- finds two extensions by Privacore
- does not find the search tool by Anonymous user b88651.

## Towards a fix

I guess that you need to somehow classify your Findx add-on as both an extension **and** a search tool. 

## Enrivonment

```text
$ date ; uname -v
Sun 20 May 2018 10:23:32 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ pkg info firefox | grep Version
Version        : 60.0.1,1
```

**Comment by brianschildt** [comment]
Thanks for the feedback - we have two extensions for Findx:

- [Findx Privacy Control](https://addons.mozilla.org/firefox/addon/findx-privacy-control/) - adding privacy and private search to the browser
- [Findx Search extension](https://addons.mozilla.org/firefox/addon/findx/) - to help you automatically choose Findx as default search engine.

We'll look into the classification part in the extensions store. @br-privacore  

Regarding the "fake" findx extension, we have reported it to Mozilla a while ago, but it apparently isn't a priority to remove it.
