### ISSUE TITLE
Cannot add Tags on Tagdb screen other than manualban, cannot delete tags or change values.

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#6]
New tags cannot be added on tagdb screen other than manualban. No tags can be deleted or have their values changed from tagdb screen. Ubuntu 14.04.5 g++ 4.9.4

**Comment by MikeLx** [comment]
Appears to work fine with g++ 6.2

**Comment by ghost** [comment]
I see the same problem. We'll look into it (it may take a few weeks).

**Comment by MikeLx** [comment]
Thanks!

**Comment by ghost** [comment]
I'm making som progress on this issue. It seems the newly added tags do hit part of the DB but then is filtered out somewhere.

**Comment by MikeLx** [comment]
I will do some more testing after upgrading to ubunutu 16 and g++ 5.4 this weekend. Thanks for working on this.

**Comment by ghost** [comment]
Findings so far:
1: The cache for tags isn't invalidated when tags are added. And the default cache timeout is 1 hour. So when you add tag "foo" it won't show up for a long while. That makes testing annoying.
2: The value entered in "urls" on the "Tagdb" page are taken as-is. But during indexing it creates tags for the "site". So entering http://s1.t11.example.com:8080/foo/boo.html will GB use incorrect database keys for the tags. Solution: enter just "s1.t11.example.com:8080" when adding tags manually.

**Comment by br-privacore** [comment]
We are curious what you are using tags for. Is it something you can share with us?

**Comment by MikeLx** [comment]
I'm using the tags to limit websites to categories, like arts, sciences, news, etc. Ordinarily, I would use collections for this. However, there is too much crossover and using collections results in burning up a good bit of disk space with redundancy. Sorry I haven't been able to do more testing. I'm fighting with a server that I have now determined has a bad board....

**Comment by ghost** [comment]
I fixed the "Tagdb" UI part. The tags are stored on the "site" part of the URLs. For instnace if the URL is "http://s1.t11.example.com:8080/t1.html" then the "site" of it is "s1.t11.example.com:8080". This is how it works during crawling and indexing.

But the Tagdb url field would take the entered value as-is and thereby store tag values with incorrect DB keys unless you know not to enter full URLs but just the site part.

The Tagdb UI now extracts the site part of any URLs and use just that. So now it works with simple copy-paste from browser URL bar.

As for the cache timeout: restart or wait one hour (or whatever "TagRec (Msg8a) cache max age" is configured to) or restart GB.

**Comment by ghost** [comment]
Two  other things: Which tag are you using? And how are you using it (GB doesn't direclty support searching on tag values)

**Comment by MikeLx** [comment]
For the moment, I just stuffed the value into the comment tag to test it. I was planning on searching on a tag value. I was thinking it was possible to search using tagdb like the original gb used catdb. Is it no longer possible to index your own metatags and search on them? I could attempt to do what I want by restricting the sites in the search. However, that limits the search to 200 sites, which isn't really enough. It's also too long and cumbersome to add thousands of sites to a search query and is limited in functionality. It is much better to limit and score a search by tag. I was planning on creating a tag for each category and giving that tag a value for how much a site applies to that category. For example:  catArts = 10, catScience = 7 for a website that is both art and science but is more art(10) than science(7.) Is there some way I can accomplish this with tagdb?

**Comment by br-privacore** [comment]
Tags are searchable in the original Gigablast. We removed it in our fork because it added a lot of unnecessary data to the index - at least for our use.

If you added e.g. a comment to tagdb, it would be stored in tagdb which in itself is not searchable. 

When re-spidering a page, it would index the words of the page and also look up the data in tagdb, and write it all to posdb to make it searchable. Since tags are site-level, and not possible to set per page, the comment would be added to all pages on that site. So if you did a search for tagcat:10, it would return all pages for all sites that had that tag set. Is this what you are looking for?

**Comment by MikeLx** [comment]
Searching for all pages that had tagcat:10 would work. Ordering on that tag would also work. I noticed that you can set up to 26 'flags" per page on the ranking page. What is this? Incidentally, I am using 26 main categories.

**Comment by br-privacore** [comment]
Right now it is not a priority to re-introduce searching on tags, but we may make it a configurable option later.

The 26 flags is work-in-progress that we will use for ranking signals from external sources.

**Comment by br-privacore** [comment]
Closing this issue as the reported problem about storing tags from the UI has been fixed.
