### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by ghost** [privacore/open-source-search-engine#63]
Hi can anyone tell me how to resolve this Error when making privacore/open-source-search-engine 
 make: *** [libcld3.so] Error 127 have installed libpcre3   is it aybe to do with the compiler version installed as per wiki  any help would be appreciated completly new to this many thanks

**Comment by br-privacore** [comment]
Are you following the exact steps documented here?
https://github.com/privacore/open-source-search-engine#migrating-gigablast-to-our-fork
(did you forget the git submodule commands perhaps?)

.. and using one of the supported operating systems?
https://github.com/privacore/open-source-search-engine#supported-platforms

we need more info on how you build and what is output before the error line you included.

**Comment by ghost** [comment]
Hi Brian thanks for the reply yes followed the instructions using ubuntu 16.04 installed     
   - g++
   - make
   - cmake
   - python
   - libpcre3-dev
   - libssl-dev
   - libprotobuf-dev
   - protobuf-compiler
   - libsqlite3-dev
   
   - libssl1.0.0
   - libpcre3
   - libprotobuf9v5
git clones okay  modules and updates ok   am trying to make file then install in gigablast 
then i make -j 2   obviously i have something wrong  or left something out your help is appreciated dave

-----Original Message-----

**Comment by br-privacore** [comment]
Please provide exact commands you use, and output (more than just the single error line).

**Comment by ghost** [comment]
Hi Brian this is what i do


-----Original Message-----

**Comment by br-privacore** [comment]
You can easily see in the output that it cannot find the "protoc" tool.

Sure you installed protobuf-compiler listed in the requirements? If so, add the path to protoc to your PATH environment variable.

**Comment by ghost** [comment]
Brian reinstalled everthing  make dist    gives me this.

-Wno-maybe-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter  -c Entities.cpp
Entities.cpp: In function ‘bool initEntityTable()’:
Entities.cpp:36:37: error: ‘s_entities’ was not declared in this scope
   const int32_t n = (int32_t)sizeof(s_entities) / (int32_t)sizeof(Entity);
                                     ^
Entities.cpp: In function ‘const Entity* getTextEntity(const char*, int32_t)’:
Entities.cpp:83:9: error: ‘s_entities’ was not declared in this scope
  return s_entities+i-1;
         ^
Entities.cpp: In function ‘int32_t getHtmlEntity(const char*, int32_t, uint32_t*, int32_t*, int32_t*)’:
Entities.cpp:206:32: error: ‘max_entity_name_len’ was not declared in this scope
  while ( len < maxLen && len < max_entity_name_len && is_alnum_a( s[len] ) ) {
                                ^
Entities.cpp:220:13: error: ‘max_entity_name_len’ was not declared in this scope
  if ( len > max_entity_name_len+1 ) {
             ^
Makefile:589: recipe for target 'Entities.o' failed
make: *** [Entities.o] Error 1
root@test:/var/www/html/open-source-search-engine#
