### ISSUE TITLE
Privacy Compromise: FindX.com Downloads from Google

### ISSUE THREAD

**Issue by martinvahi** [privacore/open-source-search-engine#64]
I'm using the Privacore issue tracker, because the 
Privacore is the core technology behind the FindX.com.

The problem that I report is that the 

https://get.findx.com/desktop/

downloads something from the 

https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,regular,italic,500,500italic,700,700italic,900,900italic

which combined with Google cookies compromises the 
privacy that the FindX is expected to provide.
I don't believe that it's intentional, I consider it a mishap,
an accidental flaw. I noticed it first, when I used the 

http://archive.is/

on the 

https://get.findx.com/desktop/

and then I verified it by using the Chromium
built-in web developer tools, the "Network" tab
that lists the download timings of different web page components.
I suspect that similar flaws might be present at some 
other FindX pages. I suggest that You run an audit about that.

Thank You for reading my comment/bug_report :-)

**Comment by brianschildt** [comment]
Thanks for reporting!   Apparently a backend update that has slipped our attention - only related to get.findx, not www.findx - I’ll try to reproduce  and solve it. I highly recommed to use the Findx privacy controller extension, then you’ll have full  transparency and protection ;-)

**Comment by martinvahi** [comment]
At some pages there's also a request to 

https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.2/TweenMax.min.js?ver=4.9.8

**Comment by br-bitberry** [comment]
https://privacore.github.io/
