### ISSUE TITLE
FindX/Privacore Feature Request: Ability to Submit seed URL Lists

### ISSUE THREAD

**Issue by martinvahi** [privacore/open-source-search-engine#65]
An example of one such list is

https://github.com/martinvahi/mmmv_notes/blob/13bdd26521ae60cafe6bfac0ee48fdb83da096fd/mmmv_notes/search_engine_seeds/seeds/mmmv_search_engine_scifi_seeds_t1.txt#L2

# Security Measures

Anti-DoS-measure that there are time limits between different submissions by SIGNED parties. At some low submission rate un-signed parties might also be able to submit URLs to the seed lists. The main challenge will be the analysis of content. For example, if someone writes a spam robot that generates vast amounts of StarTrek astronomy "science" _("fake news")_ and submits an URL to the StarTrek "science" paper collection then the generated noise will effect the quality of the search results. However, that problem is ever-present even now so some kind of automated labeling system has to be used anyway and may be someone even wants to search only the StarTrek "science". 

Wikipedia style public editing/labeling will decrease the quality to the "lowest common denominator" and dumbing things down is a really destructive form of censorship, which does not fit with the spirit of the Privacore/FindX. An example of that type of a high end failure:

https://www.nobelprize.org/prizes/physics/2013/summary/
https://www.youtube.com/watch?v=WAQqbhgwcp0&feature=youtu.be&t=31m57s

The ATLAS experiment ended up being one of the most expensive experiments at CERN

https://www.youtube.com/watch?v=I9q0XLMkeGc
https://atlas.cern/tags/higgs-boson

Given that dumber people can not recognize the ingenuity of less-dumb people, 
there is no possibility to teach a machine by showing examples. 
That rules out the machine learning techniques that require 
training data sets. I believe that an inference based approach would work, but 
that's probably too huge task for now. A compromise solution might be 
to label content by content origin and let the people/robots/whoever_who_conducts_the_search 
to specify the origin of the listed data as part of the search. For example, 

* all German universities
* all European universities
* all universities at town X
* University of Z
* science papers by non-affiliated people at field F_1
* blogs by pharmacists/physicists/IT-people
* Anything about formal verification except data by .... 
* etc.

# My Declaration of Bias

I believe that all plain-www public sites, including the FindX.com, 
are subject to supermafia/state censorship. If You do not believe it,
then try to prominently list sites that describe in detail, how to 
avoid supermafia_looting/taxes in Norway, in PublicRelations speak, 
how to "launder money" in Norway or [elsewhere](https://www.forbes.com/sites/francescoppola/2018/09/30/the-banks-that-helped-danske-bank-estonia-launder-russian-money/),
may be some detailed material about how to rape small children
would fit well to test out the Norwegian case. In China a fine test case
would probably be something that is about democracy. In Saudi-Arabia
the test case would probably be some detailed instructions about 
how to get gay sex in Saudi-Arabia without getting caught. I'm not
sure, what the Iran version would be, but I suspect that in addition to the
gay sex case some details about "extra-marital affairs" of their
clergy/mullahs might be even more effective than gay sex related
material. In Russia the details about Kremlin corruption might "do the trick".
Kremlin corruption always includes the corruption of the Czar, because
in such rigorous hierarchy corruption is not possible without the tacit 
approval of the Czar. In Germany the litmus test might be some 
hardcore Nazi material with huge swastikas. I guess raping of 
small children and torturing of pets might be the material that 
works in Estonia, which is a Good Thing, because that makes
Estonia politically less censored than Germany is. _(The worst of the
worst that one can politically use in 2018 Estonia is the Soviet Union
symbols and I haven't heard that there would have been any 
take-downs because of that reason.)_

So, the previous long section is to say that public search engines
certainly have their usefulness and a nice place in the WWW-sphere,
but they also have their INHERENT, FUNDAMENTAL shortcomings that
come from the mere fact that they are centralized and public. With that
in mind, my bias is to think about P2P-search engines and a combination
of public search engines and P2P search engines. My conclusions and 
some preliminary ideas about the combined approach are described 
at one of my very old, 2016, blog post 

https://martin.softf1.com/g/yellow_soap_opera_blog/some-thoughts-about-personalized-web-search-episode-0

and at one PRELIMINARY, NOT-YET-TESTED, PROBABLY_FLAWED
specification candidate

https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=Application+Example:+Distributed+Search+Engine

I point out that for privacy reasons a public search engine can not possibly
be personalized, but for quality reasons people should have the option
to personalize their results. In the long run the public search engines
should have some sort of a nice API that the '''personal-search-engine-clients''' 
can use, when querying a whole set of search engines, some public, some
P2P. From business model point of view the use of that API should probably
sell some single-use-query tokens that people can swap at some mix-net 
manner after the purchase. That way no crypto-currency is needed 
for anonymization. For the swapping to work, the validity of the query-tokens 
should be verifiable over the Tor network. 

## Token Swapping

The general idea is based on the idea that classical "critical section" locks can be 
implemented by a 3. thread. There are 3 threads: 2 racers, 
who want to enter the critical section, and the thread that handles the lock.
Except that in stead of 3 threads there are 3 parties:

* mixnet
* token_giver
* token_obtainer

The token fields are:

* query_token_ID
* query_token_freeze_password
* query_token_query_password

The protocol:

* token_giver gives the mixnet the query_token_ID and query_token_freeze_password.
* The mixnet contacts FindX and uses the query_token_ID and 
the query_token_freeze_password to change the  query_token_freeze_password. 
* The mixnet contacts FindX and uses the query_token_ID and 
the new query_token_freeze_password to freeze the query token.
* The mixnet tells the token_giver and the token_obtainer 
that the query token is frozen.
* The token_giver tells the token_obtainer the 
query_token_query_password.
* The token_obtainer contacts FindX and uses the query_token_query_password to 
change the query_token_query_password. 
* The token_obtainer contacts mixnet and asks the mixnet to DE-freeze the token.
* The mixnet tells the token_obtainer the query_token_freeze_password.
* The token_obtainer uses the query_token_freeze_password to 
change the query_token_freeze_password, if it wants to run the token through 
some other mixnet again.

Freezing has a timer of 1 day. If the timer expires, the freezing password will 
revert to its previous value and the token will automatically de-freeze.

At least that's just a rough draft of the token swapping protocol
that I wrote/came up with literally during the writing of this comment/feature_request. 
It has to be studied 4 possible flaws first, it's just a preliminary wild, 
POSSIBLY FLAWED idea. This preliminary, possibly flawed, draft assumes
that the FindX has an API for checking, whether the query token is still valid, unused.
Tokens should have some "best_before" date, after which they automatically
become invalid. May be 2 years might be an appropriate maximum validity time frame.
The price should be such that 1€ should buy at least 500 queries, because the 
FindX API should be very affordable. Otherwise it will not get adopted. May be
the price might depend on the maximum validity date. For example, 
one-time use query tokens that have a "shelf time" of 1 year might be 
cheaper than one-time query tokens that have a "shelf time" of 2 years.
To make the token validity queries computationally cheaper, the token
expiry date may be encoded into the token ID. To slightly anonymize the 
initial buyers of the tokens the end dates may be always some fixed day 
of the month, for example, 25. day of the month (all months have at least 25 days).

Crypto-currency based query token sales will probably never take off
within the general public and the FindX is a public, centralized, 
supermafia/state censorship victim anyway so non-crypto-currency 
based query token sales is essential. Mixnet runners can have their
own price list. May be some people do not even care to mix the
tokens with mix-nets or want to swap tokens with people, whom they
trust, like class mates, colleagues, etc.

Thank You for reading my comment :-)

**Comment by br-bitberry** [comment]
https://privacore.github.io/

**Comment by br-privacore** [comment]
We're shutting down: https://privacore.github.io/

**Comment by martinvahi** [comment]
I'm sad for the FindX demise. Easy for me to say, but 
the Gigablast was from an era, where proper database engines
were not freely available and that's probably why the original
author of the Gigablast had to write some adhoc database engine
surrogate right into the Gigablast implementation. As You now 
"too well" know, writing database engines is a lot of work, but a
search engine consists of multiple layers that are all huge projects
in their own right. The layers that I can currently identify are:

- distributed, clustered database engine, [something like](https://technology.softf1.com/software_by_third_parties/RethinkDB/2017_04_12_YouTube_qKPKsBNw604_What_is_RethinkDB.webm), the [Rethinkdb](https://github.com/rethinkdb) is.
- linquistics layer that converts human language to some intermittent language, 
a lot like compilers transform programming language to their virtual machine specific
intermittent language.
- "Artificial Intelligence" part, the part that does something with the intermittent language. 
For example, in the case of compilers the "Artificial Intelligence" analogue might be
the part that applies the various intermittent language code transformations to 
optimize the code. In the case of search engine it might be some "scene analysis",
"context based meaning extraction".
- Results presentation layer, including the various search APIs and the main "search box web page" related parts.
- Business model related software components, including supermafia/government censorship.
(Censorship free systems can not be owned/run centrally, unless they want to end up
like the old ThePirateBay ended up. ThePirateBay people have learned their 
"centralization lessons" and have created [ZeroNet](https://zeronet.io/) to replace
their centrally vulnerable hosting site.
- Scraping, extracting text from different document formats.
- Spidering strategies. Figuring out, how to move in the huge graph called the Internet. It might be a non-trival task.
- **Probably some other tasks that I'm currently (2018_11_09) too stupid to list and that Privacore/FindX people are aware of.**

I guess that the Gigablast was a really good search engine **FOR ITS TIME**, but
FindX aimed to be usable in 21. century, not at some pre-free-database-engine era.
Taking such an old C++ project for a thorough overhaul seemed to be a really bold
move from the very start and the fact that the Gigablast has just one author has
nothing to do with the fact that due to historical reasons the Gigablast was 
NOT MODULAR ENOUGH _(individually replaceable DB-layer, linquistics layer, etc.)_, 
although had it used an existing database engine in stead of using its own 
database engine analogue, the Gigablast as a whole would have not been a
"single man project" that much any more. 

Running expensive servers while the software is incomplete seems to be
the classical mistake of scaling a business before having a product to sell.
The _(money)_ burn rate goes up, but the income stream is not there due to 
the incompleteness of the product. May be in stead of a general purpose 
search engine a specialized search engine might have been a more 
attainable goal. _(Easy for me to say/speculate, hard for others to actually do it.)_

I am **NOT a Privacore/FindX/Gigablast developer, but as a bystander** it seems to me
that the FindX project got killed by lack of modularity combined with the scaling
of the business before the software was ready for use. Had the burn rate been
smaller and had the work of other people been reused in the form of components
that others have already created (database engines, linguistics, AI libraries, etc.)
the amount of original work could have been reduced to the point that a small 
team is able to create something that works really well at its niche. **An example
of a TOTAL SUCCESS of the FindX search engine was its video search 
functionality, which allowed the YouTube to be searched WITH MORE CONVENIENCE
THAN THE ORIGINAL YouTube SEARCH ITSELF ALLOWED TO SEARCH YouTube.**
Back in the day, when the Gigablast got created, YouTube did not even exist.
Also, the fact that Privacore/FindX are/were based on an open source search engine
allows the Privacore/FindX to use business models that the Google/Yahoo/Bing
CAN NOT USE and therefore CAN NOT COMPETE WITH, but the Privacore/FindX
business model tried to replicate the very same thing that had already very strong
competitors on the market. For example, one thing that the Google/Yahoo/Bing
are not able to do is to offer a local installment of some specialized index creation
software and then offer a centralized portal that allows to search all of the local indices.
For example, people/companies want to publish information about their products or some other 
things, so they have a motive to run their own software for promoting their own 
products. If the local search engine instances offer a public search API and 
the centralized "portal" uses that API, the majority of the data storage, indexing,
electrical bill is being paid by the parties who want to distribute their data to the whole
world. That arrangement also eliminates the "our-search-engine-got-banned" issue.
It is a fact that companies PAY to both, Google and Facebook to make themselves FOUND.
The payments are called "advertisement bills", just that in stead of paying for propaganda,
they would run their own instance of the open source search engine and register their
publicly available API at the central "search box portal". The same IT-company that 
maintains the office computers can use some old laptop for running a pre-prepared VirtualBox 
virtual machine that contains the local search engine instance. The local index is
pretty small anyway, so an old laptop should be able to run the search engine instance.
I have a [preliminary specification for a slightly different case](https://www.softf1.com/cgi-bin/tree1/technology/flaws/silktorrent.bash/wiki?name=Application+Example:+Distributed+Search+Engine), but
if it is slightly modified, then it might be a starting point. Again, it's easier 
said than done, a lot of empty speculation from my part, but my current 
post here is pretty speculative anyway. May be a cleaner version is that
the local search engine instance assembles some [HDF5](https://portal.hdfgroup.org/display/HDF5/HDF5) file
and that is loaded to an ordinary web hosting account, where some PHP application
serves the static index. Companies might upload those HDF5 files to the very same
web hosting accounts, where they have the company web page and the 
"central search box" portal uses the API of the HDF5 reading PHP application
like blog feed aggregators use RSS-feeds. It probably needs some clever
encoding then, may be something inspired by [Merkle trees](https://en.wikipedia.org/wiki/Merkle_tree)
that use some special purpose hash that is part of the search algorithm, like

    hash(some_string)=count_letters("a").concatct(count_letters("b")).concact(count_letters("c")). ...

Anyways, thank You for reading my post and I hope that You haven't 
totally given up on the search engine project. Even the [Doom2](https://archive.is/DLRLF) guys
didn't get it right the very first time, hence the "2" in "Doon2". Supposedly 
it took the Skype founders about 10 startups before Skype and supposedly one of the
main difference between people, who succeed and equally talented and smart
people, who fail, is that the ones, who succeed, do not give up easily, dust off
after falling, learn what went wrong and **TRY AGAIN IN SOME DIFFERENT WAY**.
