### ISSUE TITLE
Where is page actually downloaded?

### ISSUE THREAD

**Issue by dp40oz** [privacore/open-source-search-engine#8]
I'd like to add a parser that extracts only certain elements of the page to be indexed but I'm having trouble finding exactly where the page content gets downloaded. I believe its somewhere in the XmlDoc.cpp. So right after the content gets grabbed I just need it to hit my custom parser and then continue as normal. Any help in pointing me in the right direction would be great. Thanks!

**Comment by br-privacore** [comment]
You are right. Look at the function getFilteredContent in XmlDoc. This is where it decides whether a downloaded doc should be converted or not (e.g. pdf to html).
