### ISSUE TITLE
HTML Tags in Search Results

### ISSUE THREAD

**Issue by MikeLx** [privacore/open-source-search-engine#9]
Occasionally seeing a few HTML tags in search results. Mostly <p> , <div>, and  &quot; tags. Doesn't happen too often. Seems to happen mostly when there are no meta tags. May be due to improperly formatted HTML. Seems to happen most often when returning results that are portions of comments in blogs and from websites that are less professional and do not have clean HTML.

**Comment by br-privacore** [comment]
Please provide the URL of a page where this is happening so we can try reproduce it.

**Comment by MikeLx** [comment]
http://www.politico.com/story/2017/01/obama-last-press-conference-chelsea-manning-233781

**Comment by MikeLx** [comment]
H3 tags in description in this one.

Environmental Economics
<h3 style='color: #FFFFFF' ><i>The Cromulent Economics
Blog</i></h3>
www.env-econ.net/ - indexed: 1 hour ago - English

http://www.env-econ.net/

**Comment by ghost** [comment]
Hmmm. That page (env-econ) actually has escaped html tag in the og:description meta-tag.
When you click the facebook-share button then h3 tag and everything is proposed as the description. So the page description (og:description) is essentially wrong.

What we could do (but not in the near future) is to check the descriptions for html tags and if detected run the html parser on them recursively. That would generate better summaries while the pages can remain broken.

**Comment by MikeLx** [comment]
It's not a big deal. I was just pointing it out in case it was a symptom of another issue. Those tags can also be stripped out when returning results to the user via the web server that calls the api. Those tags don't take up much space in the database nor do they throw off search results that often.  It's not worth it to burn up processing power to check every page that's being spidered to catch the 1 out of 1000 that is so oddly improperly formatted.

**Comment by MikeLx** [comment]
I could also probably write that function into the native search results output. I believe that's what you were talking about in your response. Just tell me the files that I need to change I can work on it.

**Comment by ghost** [comment]
The tricky part is to filter the tags out when it is an obvious error, such as the one at the cromulent economics blog, but not filter it when the author really meant it (eg. the documentation for html at w3c.org). Our "summary expert" is back next week and will have a look.

**Comment by alc-privacore** [comment]
There are 2 places that could be a good place to filter out the html tags.
- Summary.cpp (Summary::setSummaryFromTags)
- XmlDoc.cpp (XmlDoc::getSummary - inside the if block of m_summary.setSummaryFromTags)

Similar logic could be implemented for title in Title.cpp (Title::setTitleFromTags) or XmlDoc.cpp (XmlDoc::getTitle)

**Comment by MikeLx** [comment]
Thanks. I think this will be relatively easy. On a related topic, if I want to parse out certain values from the html, like article dates in news articles (which can be different from the spider date,) and insert those values into tagdb or update the spider date with that date, what files do I start with? I assume the same ones as above plus the files to insert the value into tagdb and/or update the spiderdb date.

**Comment by alc-privacore** [comment]
You probably don't want to insert it into tagdb, it's per 'site' and not per document.
I would say XmlDoc.cpp or XmlDoc_Indexing.cpp would be a good start. Spider.cpp if you want to add it to the spiderdb. However, titledb might be another place to store it depending on what you're planning to do with the date.
